# Nivell 1 - EDA estructurat i neteja bàsica

# Exercici 1: Exploració inicial del dataset

Importamos las librerias que iremos usando a lo largo de los codigos e importamos el fichero excel.

In [ ]:
import pandas as pd
import json
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

def leer_fichero(ruta="sprint8_complex.xlsx"):
  df = pd.read_excel(ruta)
  return df

In [ ]:
df = leer_fichero('/content/drive/MyDrive/Colab Notebooks/sprint8_complex.xlsx')
df.head()

,Dades de l'enquesta de treballadors 2025,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19
0,Generades aleatòriament per seguretat,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional,CÃ rrec,Nombre_fills,Te_cotxe,Km_anuals,Consum_mitja_L_100km,Temperatura_mitjana_ciutat
3,0,Joana,Gil Navarro,66722344X,Espanya,Valladolid,23.0,3.0,1958.0,Dona,"1,469 â‚¬",True,NaN,Grup B,Cap de projecte,3.0,True,32108.0,25.0,10.1
4,1,Marc,MuÃ±oz,48840994W,Espanya,Alacant,8.0,11.0,1960.0,H,"2,718 â‚¬",NaN,True,Grup C,Senior analyst,0.0,True,19496.0,10.4,18.7

> Quantes files i columnes té el dataset?


Usando shape, vemos que hay 1010 filas y 20 columnas

In [ ]:
df.shape

(1010, 20)

> Mostra representativa de files

Como el fichero es grande no basta con una muestra de las primeras y ultimas filas, es interesante coger algunas filas más para revisar la coherencia de datos.

Uniremos las 5 primeras filas con head(), 10 filas aleatorias con sample(10), y las últimas 5 con tail().

In [ ]:
df_muestra = pd.concat([df.head(), df.sample(10), df.tail()])
display(df_muestra)

,Dades de l'enquesta de treballadors 2025,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19
0,Generades aleatòriament per seguretat,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional,CÃ rrec,Nombre_fills,Te_cotxe,Km_anuals,Consum_mitja_L_100km,Temperatura_mitjana_ciutat
3,0,Joana,Gil Navarro,66722344X,Espanya,Valladolid,23.0,3.0,1958.0,Dona,"1,469 â‚¬",True,NaN,Grup B,Cap de projecte,3.0,True,32108.0,25.0,10.1
4,1,Marc,MuÃ±oz,48840994W,Espanya,Alacant,8.0,11.0,1960.0,H,"2,718 â‚¬",NaN,True,Grup C,Senior analyst,0.0,True,19496.0,10.4,18.7
985,982,Carlos,GÃ³mez Navarro,40048229A,Espanya,Sevilla,19.0,7.0,1975.0,Dona,dos mil,NaN,True,Grup B,Responsable de vendes,0.0,False,NaN,NaN,15.7
491,488,NÃºria,Soler FernÃ¡ndez,35809507W,Espanya,Palma,26.0,9.0,1985.0,D,"1,711 â‚¬",NaN,True,Grup B,Analista,0.0,False,NaN,NaN,NaN
436,433,Anna,SÃ¡nchez,57957055W,Espanya,Murcia,32.0,0.0,1940.0,D,1078â‚¬,True,NaN,Grup A,Administratiu,1,True,80000,7.4,18.8
512,509,Xavier,Romero Ãlvarez,38277083J,Espanya,Murcia,2.0,3.0,1969.0,D,"2,952 â‚¬",True,NaN,Grup C,Cap de projecte,1.0,False,NaN,NaN,NaN
807,804,Marc,LÃ³pez Costa,11828041P,Espanya,Sevilla,30.0,8.0,1980.0,M,2406 euros,NaN,NaN,Grup C,Responsable de vendes,NaN,NaN,NaN,NaN,16.5
496,493,Marina,Ribera,68589370R,Espanya,Palma,11.0,4.0,1980.0,F,"1,385 â‚¬",NaN,True,Grup B,Senior analyst,0.0,True,18378.0,NaN,18.6
292,289,Nil,Pujol,69338400X,Espanya,Alacant,24.0,10.0,1967.0,D,"1,079 â‚¬",True,True,Grup A,Analista junior,0,NaN,NaN,NaN,17.8
239,236,Leon,MÃ¼ller,92189839F,Alemanya,Hamburg,19.0,10.0,1975.0,H,3552â‚¬,NaN,True,Grup D,Senior analyst,NaN,False,NaN,NaN,6.6
481,478,AdriÃ,Ãlvarez,51706253M,Espanya,Zaragoza,20.0,5.0,1974.0,D,"1,027 â‚¬",NaN,True,Grup A,TÃ¨cnic IT,NaN,NaN,NaN,NaN,15.0
575,572,Sergio,Roca LÃ³pez,31236454Q,Espanya,A CoruÃ±a,18.0,2.0,1993.0,H,1035â‚¬,True,NaN,Grup A,Analista junior,1.0,False,NaN,NaN,17.3
1005,1002,Alba,MuÃ±oz,97954019T,Espanya,Bilbao,25.0,10.0,1983.0,D,"1,409 â‚¬",NaN,True,Grup B,Responsable de vendes,0.0,NaN,NaN,NaN,14.7
1006,1003,Claudia,Gil Ferrer,55297384F,Espanya,ValÃ¨ncia,1.0,11.0,1981.0,H,1.789 â‚¬,NaN,True,Grup B,Responsable de vendes,0.0,True,29952.0,9.2,20.3
1007,1004,Oriol,Ferrer,52590001R,Espanya,Zaragoza,15.0,7.0,1973.0,D,786â‚¬,NaN,True,Grup A,Analista,0.0,True,81381.0,6.5,13.9
1008,1005,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1009,1006,???,###,XXXX,Narnia,Desconeguda,-99.0,99.0,3000.0,??,molts,NaN,NaN,Z,???,NaN,NaN,NaN,NaN,NaN

 Establecemos la tercera fila como encabezado.

In [ ]:
df = pd.read_excel('/content/drive/MyDrive/Colab Notebooks/sprint8_complex.xlsx', header=3)

> Quin tipus de dades conté cada columna?

In [ ]:
df.dtypes.value_counts()

object     12
float64     7
int64       1
Name: count, dtype: int64

El metodo info nos permite revisar si hay coherencia entre los nombres de la columnas y su tipo, y tambien nos proporciona indicadores de que hay muchos valores faltantes o nulos en el archivo.

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1007 entries, 0 to 1006
Data columns (total 20 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Unnamed: 0                  1007 non-null   int64
 1   Nom                         1006 non-null   object
 2   Cognoms                     1006 non-null   object
 3   DNI                         1006 non-null   object
 4   País d'origen               1006 non-null   object
 5   Ciutat                      1006 non-null   object
 6   Dia de Naixement            1006 non-null   float64
 7   Mes de Naixement            1006 non-null   float64
 8   Any de Naixement            1006 non-null   float64
 9   Gènere                      966 non-null    object
 10  Salari mensual              1006 non-null   object
 11  Fills                       419 non-null    object
 12  No Fills                    585 non-null    object
 13  Grup Professional           1005 non-null   object
 14  CÃ rrec                     1005 non-null   object
 15  Nombre_fills                709 non-null    float64
 16  Te_cotxe                    658 non-null    object
 17  Km_anuals                   315 non-null    float64
 18  Consum_mitja_L_100km        261 non-null    float64
 19  Temperatura_mitjana_ciutat  936 non-null    float64
dtypes: float64(7), int64(1), object(12)
memory usage: 157.5+ KB

No consta ninguna columna de tipo booleano, sin embargo te_cotxe, fills, no_fills muestran celdas indicando "True" o "False".

Conviene revisar el tipo de las celdas.

Vemos que estan mezcladas y por ese motivo, Pandas les ha asignado el tipo genérico object.

In [ ]:
te_cotxe = df['Te_cotxe'].apply(type).unique()
fills = df['Fills'].apply(type).unique()
no_fills = df['No Fills'].apply(type).unique()

print(te_cotxe, fills, no_fills)

[<class 'bool'> <class 'float'>] [<class 'bool'> <class 'float'>] [<class 'float'> <class 'bool'>]

Contaremos los valores NaN de cada columna

In [ ]:
df.isna().sum()

Unnamed: 0                      0
Nom                             1
Cognoms                         1
DNI                             1
País d'origen                   1
Ciutat                          1
Dia de Naixement                1
Mes de Naixement                1
Any de Naixement                1
Gènere                         41
Salari mensual                  1
Fills                         588
No Fills                      422
Grup Professional               2
CÃ rrec                         2
Nombre_fills                  298
Te_cotxe                      349
Km_anuals                     692
Consum_mitja_L_100km          746
Temperatura_mitjana_ciutat     71
dtype: int64

Miramos la proporcion de Nan de cada columna

Algunas columnas tienen mas NAN que valores válidos, ex: Fills, Km_anuals, Consum_mitja_L_100km.

In [ ]:
df.isna().mean()*100

Unnamed: 0                     0.000000
Nom                            0.099305
Cognoms                        0.099305
DNI                            0.099305
País d'origen                  0.099305
Ciutat                         0.099305
Dia de Naixement               0.099305
Mes de Naixement               0.099305
Any de Naixement               0.099305
Gènere                         4.071500
Salari mensual                 0.099305
Fills                         58.391261
No Fills                      41.906653
Grup Professional              0.198610
CÃ rrec                        0.198610
Nombre_fills                  29.592850
Te_cotxe                      34.657398
Km_anuals                     68.718967
Consum_mitja_L_100km          74.081430
Temperatura_mitjana_ciutat     7.050645
dtype: float64

> Hi ha files duplicades?

Si buscamos duplicados leyendo las 20 columnas, no hay duplicados.

Sin embargo, obviando la columna Unnamed: 0, que se asemeja a un ID de registro asignado automaticamente (el excel menciona "Generades aleatòriament per seguretat") si que podemos llegar a detectar filas duplicadas.

Usaremos el método duplicated() y encontramos 4 filas.

In [ ]:
# comprobamos que cada fila tiene un registro propio, que el mismo numero no este repetido.
print(df['Unnamed: 0'].is_unique)

True

In [ ]:
df_bis = df.iloc[:, 1:] # permite selectionar todas las columnas a partir de la columna index 1 , asi obviamos Unnamed:0
df_bis[df_bis.duplicated(keep=False)] # filtramos el dataframe mostrando solo los duplicados

,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional,CÃ rrec,Nombre_fills,Te_cotxe,Km_anuals,Consum_mitja_L_100km,Temperatura_mitjana_ciutat
36,Ida,Karlsen Eriksen,55283701C,Noruega,Oslo,2.0,9.0,1992.0,D,"1,614 â‚¬",True,NaN,Grup B,Analista,3.0,NaN,NaN,NaN,10.6
40,Ida,Karlsen Eriksen,55283701C,Noruega,Oslo,2.0,9.0,1992.0,D,"1,614 â‚¬",True,NaN,Grup B,Analista,3.0,NaN,NaN,NaN,10.6
372,Alba,MuÃ±oz,97954019T,Espanya,Bilbao,25.0,10.0,1983.0,D,"1,409 â‚¬",NaN,True,Grup B,Responsable de vendes,0.0,NaN,NaN,NaN,14.7
730,Claudia,Gil Ferrer,55297384F,Espanya,ValÃ¨ncia,1.0,11.0,1981.0,H,1.789 â‚¬,NaN,True,Grup B,Responsable de vendes,0.0,True,29952.0,9.2,20.3
757,Oriol,Ferrer,52590001R,Espanya,Zaragoza,15.0,7.0,1973.0,D,786â‚¬,NaN,True,Grup A,Analista,0.0,True,81381.0,6.5,13.9
1002,Alba,MuÃ±oz,97954019T,Espanya,Bilbao,25.0,10.0,1983.0,D,"1,409 â‚¬",NaN,True,Grup B,Responsable de vendes,0.0,NaN,NaN,NaN,14.7
1003,Claudia,Gil Ferrer,55297384F,Espanya,ValÃ¨ncia,1.0,11.0,1981.0,H,1.789 â‚¬,NaN,True,Grup B,Responsable de vendes,0.0,True,29952.0,9.2,20.3
1004,Oriol,Ferrer,52590001R,Espanya,Zaragoza,15.0,7.0,1973.0,D,786â‚¬,NaN,True,Grup A,Analista,0.0,True,81381.0,6.5,13.9

> Les dades semblen coherents a primera vista? » Detectes possibles problemes o inconsistències evidents?

Segun los metodos de analisis aplicados hasta ahora observamos:

   **Problema de codificacion** : no se leen bien los caracteres especiales

   **Tipos de datos incorrectos**

Columnas cuyos datos deberian ser de tipo numero entero:
*   Dia de Naixement
*   Mes de Naixement
*   Any de Naixement
*   Nombre_fills

Columnas cuyos datos deberian ser de tipo decimal:
*   Salari mensual

Columnas cuyos datos deberian ser booleanos:
*   Fills
*   No Fills
*   Te_cotxe

   **Errores en columnas**
*   Fills y No Fills podrian unificarse
*   CÃ rrec está mal escrita.

   **Datos inconsistentes**
*   Genere contiene datos que significan lo mismo aunque escritas de distintas formas: "Dona", "D", "F"
*  Poca seriedad en los datos de la ultima fila, ex: pais "Narnia", genere "??"


Generaremos un resumen de datos con el metodo describe para sacar más información.

In [ ]:
df.describe()

,Unnamed: 0,Dia de Naixement,Mes de Naixement,Any de Naixement,Nombre_fills,Km_anuals,Consum_mitja_L_100km,Temperatura_mitjana_ciutat
count,1007.000000,1006.000000,1006.000000,1006.000000,709.000000,315.000000,261.000000,936.000000
mean,503.000000,15.027833,8.556660,2002.229622,1.203103,55951.050794,11.024521,15.379167
std,290.840162,10.327436,14.298532,143.118077,1.389404,62095.437005,8.775557,7.276425
min,0.000000,-99.000000,0.000000,1940.000000,0.000000,-50.000000,0.500000,-10.000000
25%,251.500000,7.000000,3.250000,1969.000000,0.000000,22632.000000,4.700000,12.800000
50%,503.000000,15.000000,6.000000,1982.000000,1.000000,56135.000000,9.800000,15.500000
75%,754.500000,24.000000,10.000000,1995.000000,2.000000,80000.000000,13.600000,18.300000
max,1006.000000,32.000000,99.000000,3000.000000,5.000000,1000000.000000,25.000000,42.000000

**Valores fuera de rango**

  * día de nacimiento: min -99 y max 32 (el rango de dias es de 1 a 31).
  * mes de nacimiento: min 0 y max 99 (el rango de meses es de 1 a 12).
  * año de nacimiento: min 1940 y max 3000 (es poco probable que una persona nacida en 1940 siga trabajando, y es imposible que sea superior a 2026).
  * Km_anuals: min -50 km y max 1.000.000 (no deberia ser negativo, y el valor maximo es improbable)

# Ejercicio 2: Validacions bàsiques de les dades i decisions d'eliminació

> Corregir possibles problemes de codificació i accentuació en els noms de les columnes i en els valors de text, si escau.

Hice algunos intentos y me encontre con varios problemas:

1. Primero empece usando el metodo str.encode, pero el dataframe tambien contiene valores numericos y booleanos. Debemos ignorarlos.
2. Trate de re-codificar a latin-1, pero algunos caracteres no estaban contemplados. Usare cp1252.
3. Intente arreglar todo el dataframe de golpe, pero al haber celda corectas e incorectas mezcladas, generaba fallos. Procederemos elemento por elemento y si una celda es correcta la dejamos intacta.

Por otro lado, al habar detectado unicamente un nombre de columna con error de codificacion, la modificaremos directamente.
Y tambien aprobechamos para cambiar el nombre de la columna "Unnamed: 0" por "ID"

In [ ]:
df = df.rename(columns={"CÃ\xa0rrec": "Càrrec"})

In [ ]:
df = df.rename(columns={"Unnamed: 0": "ID"})

In [ ]:
def corregir_mojibake(valor):
    # Si el valor no es string (NaN, numeros), se descarta.
    if not isinstance(valor, str):
        return valor

    try:
        # Se recodifica en CP1252 y decodifica en UTF-8
        return valor.encode('cp1252').decode('utf-8')
    except (UnicodeEncodeError, UnicodeDecodeError):
        # Si el valor está bien escrito dará error al intentar re-codificar; en ese caso lo dejamos tal cual
        return valor

# Aplicamos la corrección unicamente a las columnas de tipo texto (object)
columnas_texto = df.select_dtypes(include=['object']).columns

for col in columnas_texto:
    try:
        # Aplicamos el cambio celda por celda con .map()
        df[col] = df[col].map(corregir_mojibake)

        print(f"'{col}' corregida.")
    except Exception as e:
        print(f" Error '{col}': {e}")

'Nom' corregida.
'Cognoms' corregida.
'DNI' corregida.
'País d'origen' corregida.
'Ciutat' corregida.
'Gènere' corregida.
'Salari mensual' corregida.
'Fills' corregida.
'No Fills' corregida.
'Grup Professional' corregida.
'Càrrec' corregida.
'Te_cotxe' corregida.

In [ ]:
df_muestra = pd.concat([df.head(), df.sample(10), df.tail()])
display(df_muestra)

,ID,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional,Càrrec,Nombre_fills,Te_cotxe,Km_anuals,Consum_mitja_L_100km,Temperatura_mitjana_ciutat
0,0,Joana,Gil Navarro,66722344X,Espanya,Valladolid,23.0,3.0,1958.0,Dona,"1,469 €",True,NaN,Grup B,Cap de projecte,3.0,True,32108.0,25.0,10.1
1,1,Marc,Muñoz,48840994W,Espanya,Alacant,8.0,11.0,1960.0,H,"2,718 €",NaN,True,Grup C,Senior analyst,0.0,True,19496.0,10.4,18.7
2,2,Noa,Serra,14308421X,Espanya,Alacant,27.0,4.0,1961.0,D,1358 euros,True,NaN,Grup A,Tècnic IT,4.0,NaN,NaN,NaN,16.7
3,3,Pol,Gil,58586340F,Espanya,Sevilla,13.0,10.0,1985.0,H,"1,478 €",True,NaN,Grup B,Data Analyst,2.0,False,NaN,NaN,18.3
4,4,David,Vila,82070937P,Espanya,Bilbao,29.0,11.0,1965.0,Dona,"1,284 €",NaN,True,Grup B,Administratiu,NaN,True,NaN,11.8,13.1
673,673,Noa,Costa,48547666Z,Espanya,València,1.0,3.0,1982.0,D,"2,392 €",True,NaN,Grup C,Responsable de vendes,1.0,NaN,NaN,NaN,NaN
260,260,Elena,Moretti Giordano,46138183J,Itàlia,Torino,17.0,12.0,1973.0,D,1023€,True,NaN,Grup A,Administratiu,4.0,True,80000.0,25.0,17.7
257,257,Adrià,Serra,92072899Q,Espanya,Alacant,1.0,10.0,1963.0,H,"1,292 €",True,True,Grup A,Tècnic IT,0.0,NaN,NaN,NaN,18.2
670,670,Ben,Richter Becker,84198784R,Alemanya,Köln,20.0,2.0,1968.0,Dona,"1,939 €",NaN,True,Grup B,Cap de projecte,NaN,True,80000.0,4.9,9.5
801,801,Sara,Navarro,77970791L,Espanya,Barcelona,7.0,4.0,1978.0,M,"1,497 €",NaN,True,Grup B,Analista,NaN,NaN,NaN,NaN,14.2
869,869,Nil,Fernández Ramos,34385885F,Espanya,Màlaga,11.0,11.0,1995.0,D,823 €,NaN,True,Grup A,Analista junior,NaN,False,NaN,NaN,16.9
975,975,Alba,Díaz,61448694R,Espanya,Madrid,6.0,11.0,1987.0,D,950€,True,NaN,Grup A,Cap de Projecte,1.0,True,80000.0,0.5,19.0
91,91,Alexia,Gil,89968863W,Espanya,Palma,25.0,11.0,1973.0,NaN,2.257 €,True,NaN,Grup C,Responsable de vendes,1.0,True,80000.0,11.5,17.7
704,704,Anna,Domènech Navarro,48548665G,Espanya,Tarragona,4.0,7.0,1971.0,Dona,"1,309 €",NaN,True,Grup A,Cap de projecte,0.0,False,NaN,NaN,17.4
552,552,Adrià,Ribera,99152055K,Espanya,Sevilla,4.0,11.0,1981.0,H,"1,698 €",True,NaN,Grup B,Project lead,4.0,False,NaN,NaN,NaN
1002,1002,Alba,Muñoz,97954019T,Espanya,Bilbao,25.0,10.0,1983.0,D,"1,409 €",NaN,True,Grup B,Responsable de vendes,0.0,NaN,NaN,NaN,14.7
1003,1003,Claudia,Gil Ferrer,55297384F,Espanya,València,1.0,11.0,1981.0,H,1.789 €,NaN,True,Grup B,Responsable de vendes,0.0,True,29952.0,9.2,20.3
1004,1004,Oriol,Ferrer,52590001R,Espanya,Zaragoza,15.0,7.0,1973.0,D,786€,NaN,True,Grup A,Analista,0.0,True,81381.0,6.5,13.9
1005,1005,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1006,1006,???,###,XXXX,Narnia,Desconeguda,-99.0,99.0,3000.0,??,molts,NaN,NaN,Z,???,NaN,NaN,NaN,NaN,NaN

> Detectar i eliminar files duplicades exactes, indicant quants registres s'han eliminat.

Anteriormente detectamos 4 filas duplicadas enteras.
Las eliminamos y comprobamos que:
- no quedan duplicados
- se ha conservado un registro de cada fila
- de 1007 filas, quedan 1003.

In [ ]:
df_bis = df.iloc[:, 1:] # obviamos Unnamed:0
df_bis[df_bis.duplicated(keep=False)] # filtramos el dataframe mostrando solo los duplicados

,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional,Càrrec,Nombre_fills,Te_cotxe,Km_anuals,Consum_mitja_L_100km,Temperatura_mitjana_ciutat
36,Ida,Karlsen Eriksen,55283701C,Noruega,Oslo,2.0,9.0,1992.0,D,"1,614 €",True,NaN,Grup B,Analista,3.0,NaN,NaN,NaN,10.6
40,Ida,Karlsen Eriksen,55283701C,Noruega,Oslo,2.0,9.0,1992.0,D,"1,614 €",True,NaN,Grup B,Analista,3.0,NaN,NaN,NaN,10.6
372,Alba,Muñoz,97954019T,Espanya,Bilbao,25.0,10.0,1983.0,D,"1,409 €",NaN,True,Grup B,Responsable de vendes,0.0,NaN,NaN,NaN,14.7
730,Claudia,Gil Ferrer,55297384F,Espanya,València,1.0,11.0,1981.0,H,1.789 €,NaN,True,Grup B,Responsable de vendes,0.0,True,29952.0,9.2,20.3
757,Oriol,Ferrer,52590001R,Espanya,Zaragoza,15.0,7.0,1973.0,D,786€,NaN,True,Grup A,Analista,0.0,True,81381.0,6.5,13.9
1002,Alba,Muñoz,97954019T,Espanya,Bilbao,25.0,10.0,1983.0,D,"1,409 €",NaN,True,Grup B,Responsable de vendes,0.0,NaN,NaN,NaN,14.7
1003,Claudia,Gil Ferrer,55297384F,Espanya,València,1.0,11.0,1981.0,H,1.789 €,NaN,True,Grup B,Responsable de vendes,0.0,True,29952.0,9.2,20.3
1004,Oriol,Ferrer,52590001R,Espanya,Zaragoza,15.0,7.0,1973.0,D,786€,NaN,True,Grup A,Analista,0.0,True,81381.0,6.5,13.9

In [ ]:
df.drop([36, 372, 757, 730], inplace=True)

In [ ]:
df[df['DNI'].isin(['97954019T', '55283701C', '55297384F', '52590001R'])]

,ID,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional,Càrrec,Nombre_fills,Te_cotxe,Km_anuals,Consum_mitja_L_100km,Temperatura_mitjana_ciutat
40,1001,Ida,Karlsen Eriksen,55283701C,Noruega,Oslo,2.0,9.0,1992.0,D,"1,614 €",True,NaN,Grup B,Analista,3.0,NaN,NaN,NaN,10.6
1002,1002,Alba,Muñoz,97954019T,Espanya,Bilbao,25.0,10.0,1983.0,D,"1,409 €",NaN,True,Grup B,Responsable de vendes,0.0,NaN,NaN,NaN,14.7
1003,1003,Claudia,Gil Ferrer,55297384F,Espanya,València,1.0,11.0,1981.0,H,1.789 €,NaN,True,Grup B,Responsable de vendes,0.0,True,29952.0,9.2,20.3
1004,1004,Oriol,Ferrer,52590001R,Espanya,Zaragoza,15.0,7.0,1973.0,D,786€,NaN,True,Grup A,Analista,0.0,True,81381.0,6.5,13.9

In [ ]:
df.shape

(1003, 20)

> Comprovar la unicitat del DNI.
En cas de detectar DNIs duplicats, hauràs d'analitzar la coherència de la informació associada i descartar o anul·lar els registres que no siguin fiables, justificant clarament la decisió presa.

In [ ]:
df[df.duplicated(subset=['DNI'], keep=False)].sort_values('DNI')

,ID,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional,Càrrec,Nombre_fills,Te_cotxe,Km_anuals,Consum_mitja_L_100km,Temperatura_mitjana_ciutat
250,250,Laia,Navarro Vila,15909601K,Espanya,Bilbao,30.0,5.0,1958.0,D,1235 euros,True,True,Grup D,Analista junior,0.0,False,NaN,NaN,10.3
604,604,Laia,Navarro,15909601K,Espanya,Bilbao,30.0,5.0,1958.0,D,"1,676 €",True,False,Grup A,Analista,1.0,True,50.0,NaN,14.2
654,654,Oriol,Gómez,16618423V,Espanya,Madrid,10.0,1.0,1968.0,Home,1731 euros,True,NaN,Grup B,Data analyst,4.0,NaN,NaN,NaN,NaN
754,754,Oriol,Gómez,16618423V,Espanya,Barcelona,10.0,1.0,1968.0,Home,2.358 €,True,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN
758,758,Oriol,Gómez,16618423V,Espanya,Màlaga,10.0,1.0,1968.0,H,1879 euros,True,NaN,Grup B,Data Analyst,4.0,False,NaN,NaN,NaN
759,759,Oriol,Gómez,16618423V,Espanya,Sevilla,10.0,1.0,1968.0,NaN,"2,000 €",NaN,NaN,Grup A,Responsable de vendes,5.0,NaN,NaN,NaN,20.7
558,558,Alexia,Pérez Díaz,49529438G,Espanya,Màlaga,12.0,10.0,1981.0,Dona,"1,176 €",NaN,True,Grup A,Data Analyst,0.0,False,NaN,NaN,38.0
692,692,Alexia,Pérez Díaz,49529438G,Espanya,Màlaga,12.0,10.0,1981.0,Dona,1663€,NaN,True,Grup C,Cap de projecte,NaN,True,80000.0,10.7,16.9
89,89,Guillem,Pujol Costa,54013571W,Espanya,A Coruña,17.0,7.0,1983.0,D,1.574 €,True,NaN,Grup B,Project lead,4.0,False,NaN,NaN,14.6
142,142,Marta,Ruiz,54013571W,Espanya,Palma,24.0,5.0,1982.0,H,"1,276 €",True,True,Grup A,Analista,0.0,False,NaN,NaN,15.7
25,25,Sara,Serra,90585882A,Espanya,Tarragona,28.0,5.0,2002.0,D,993 €,NaN,True,Grup A,Administratiu,0.0,False,NaN,NaN,15.8
104,104,Oriol,Vila Casals,90585882A,Espanya,Madrid,30.0,9.0,1964.0,H,1987 euros,NaN,True,Grup B,Responsable de vendes,0.0,False,NaN,NaN,13.5
114,114,Pol,Serra,90585882A,Espanya,Girona,4.0,12.0,1960.0,H,"1,178 €",NaN,True,Grup A,Data Analyst,NaN,False,NaN,NaN,16.2
281,281,Xavier,Vidal,90585882A,Espanya,Alacant,2.0,7.0,1958.0,H,1179 euros,NaN,NaN,Grup A,Tècnic IT,0.0,True,63574.0,6.0,16.8
913,913,Sara,Serra,90585882A,Espanya,Tarragona,28.0,5.0,2002.0,Dona,"1,000 €",NaN,True,Grup A,Administratiu,0.0,False,NaN,NaN,15.8
1000,1000,Sara,Serra,90585882A,Espanya,Tarragona,28.0,5.0,2002.0,D,"1,073 €",NaN,True,Grup A,Administratiu,0.0,False,NaN,NaN,15.8

Hay 5 DNIS repetidos con 2 diferentes casuisticas:

**Caso 1** Parece que el mismo empleado ha rellenado la encuesta varias veces a lo largo de su carrera en la empresa. Observamos un cargo distinto, un sueldo superior, o un incremento en el numero de hijos.
Conservaremos la fila con el indice más reciente, y trataremos de no perder informacion de los campos clave

15909601K - 604 (eliminamos 250)

49529438G - 692 (eliminamos 558)

16618423V - 759 (eliminamos 654,754,758)

**Caso 2** El mismo DNI está registrado bajo personas distintas.

54013571W (repetido 2 veces)

90585882A (repetido 6 veces)

Disponiendo unicamente de este dataset, no podemos determinar cuales son las filas validas y cuales no, por lo que no podemos conservar y descartar arbitrariamente una fila como si fueran filas duplicadas exactas.

Por otro lado, conservar estos registros inconsistentes falsarian el analisis.

Si no sabemos como descartar y tampoco podemos guardar estos duplicados, tendremos que eliminarlos.

In [ ]:
# CASO 1 - 1. Analizamos las filas duplicadas entre si, revisamos consistencia en los campos claves
df.loc[[604, 250]]
df.loc[[692, 558]]
df.loc[[759, 654, 754, 758]]

,ID,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional,Càrrec,Nombre_fills,Te_cotxe,Km_anuals,Consum_mitja_L_100km,Temperatura_mitjana_ciutat
759,759,Oriol,Gómez,16618423V,Espanya,Sevilla,10.0,1.0,1968.0,NaN,"2,000 €",NaN,NaN,Grup A,Responsable de vendes,5.0,NaN,NaN,NaN,20.7
654,654,Oriol,Gómez,16618423V,Espanya,Madrid,10.0,1.0,1968.0,Home,1731 euros,True,NaN,Grup B,Data analyst,4.0,NaN,NaN,NaN,NaN
754,754,Oriol,Gómez,16618423V,Espanya,Barcelona,10.0,1.0,1968.0,Home,2.358 €,True,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN
758,758,Oriol,Gómez,16618423V,Espanya,Màlaga,10.0,1.0,1968.0,H,1879 euros,True,NaN,Grup B,Data Analyst,4.0,False,NaN,NaN,NaN

In [ ]:
# CASO 1 - 2. Introducimos los valores faltantes de los campos en las filas que conservaremos
df.loc[604, 'Cognoms'] = "Navarro Vila"
df.loc[759, 'Gènere'] = "Home"

In [ ]:
# CASO 1 - 3. eliminamos las filas más antiguas
df.drop([250,558,654,754,758], inplace=True)

In [ ]:
# CASO 1 - 4. revisamos que cada DNI solo queda en las filas más recientes
df[df["DNI"].isin(['15909601K', '49529438G', '16618423V'])]

,ID,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional,Càrrec,Nombre_fills,Te_cotxe,Km_anuals,Consum_mitja_L_100km,Temperatura_mitjana_ciutat
604,604,Laia,Navarro Vila,15909601K,Espanya,Bilbao,30.0,5.0,1958.0,D,"1,676 €",True,False,Grup A,Analista,1.0,True,50.0,NaN,14.2
692,692,Alexia,Pérez Díaz,49529438G,Espanya,Màlaga,12.0,10.0,1981.0,Dona,1663€,NaN,True,Grup C,Cap de projecte,NaN,True,80000.0,10.7,16.9
759,759,Oriol,Gómez,16618423V,Espanya,Sevilla,10.0,1.0,1968.0,Home,"2,000 €",NaN,NaN,Grup A,Responsable de vendes,5.0,NaN,NaN,NaN,20.7

In [ ]:
# CASO 2 - 1. revisamos en cuantas filas aparecen los 2 DNIs
df["DNI"].isin(['54013571W', '90585882A']).sum()

np.int64(8)

In [ ]:
# CASO 2 - 2. las eliminamos y comprobamos
eliminar_dni = df[df["DNI"].isin(['54013571W', '90585882A'])]
df.drop(eliminar_dni.index, inplace=True)
df[df["DNI"].isin(['54013571W', '90585882A'])]

Empty DataFrame
Columns: [ID, Nom, Cognoms, DNI, País d'origen, Ciutat, Dia de Naixement, Mes de Naixement, Any de Naixement, Gènere, Salari mensual, Fills, No Fills, Grup Professional, Càrrec, Nombre_fills, Te_cotxe, Km_anuals, Consum_mitja_L_100km, Temperatura_mitjana_ciutat]
Index: []

In [ ]:
df.shape

(990, 20)

Hemos eliminado 13 filas en total, de 1003 filas, quedan 990.

> Identificar els camps clau que no haurien de contenir valors nuls, detectar registres amb informació insuficient i eliminar únicament aquelles files completament buides o amb informació irrecuperable o no substituïble, explicant per què no és possible ni raonable imputar-les.

Miramos cuantos valores NaN tiene cada columna para valorar que campos son críticos para el análisis.

In [ ]:
df.isnull().sum().sort_values(ascending=False)

Consum_mitja_L_100km          732
Km_anuals                     678
Fills                         578
No Fills                      416
Te_cotxe                      345
Nombre_fills                  297
Temperatura_mitjana_ciutat     68
Gènere                         40
Salari mensual                  1
DNI                             1
Cognoms                         1
Nom                             1
Ciutat                          1
Any de Naixement                1
Dia de Naixement                1
Mes de Naixement                1
Càrrec                          1
País d'origen                   1
Grup Professional               1
ID                              0
dtype: int64

In [ ]:
df[df["DNI"].isna()]

,ID,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional,Càrrec,Nombre_fills,Te_cotxe,Km_anuals,Consum_mitja_L_100km,Temperatura_mitjana_ciutat
1005,1005,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Las celdas donde NaN = 1, son todas de la fila 1005. Esta fila no aporta ningun valor al dataset, la eliminamos.

In [ ]:
df.drop(index=1005, inplace=True)

In [ ]:
df.shape

(989, 20)

Quedan actualmente 989 filas en el dataframe, podemos ver que desde "Nom" hasta "Grup Professional" todas las columnas contienen un valor válido, estas columnas son las que establecen la identificación del empleado.

Podriamos establecer estos 11 campos como claves. Aunque en realidad, solo hay un campo unico que permite relacionar una fila con un empleado, y se trata del DNI.

Las columnas que tienen muchos valores nulos no son críticos para la identificación del empleado ni parecen ser relevantes para la encuesta, desconociendo el proposito de esta última es dificil aportar conclusiones al respecto.

Otros apuntes:

- Se entiende que "Gènere" pueda contener valores nulos dado que hay personas que prefieren no comunicarlo.
- "Temperatura_mitjana_ciutat" es algo ambiguo, a que ciudad nos referimos? al lugar de trabajo, al domicilio, a la ciudad de la columna "ciutat"? por eso mismo tambien podemos entender que algunos empleados no hayan rellenado el campo sin contar con el hecho de que no es un dato propio del empleado.
- Hay columnas que dependen de otras: "Nombre_fills" dependerá de "Fills"/"No Fills" así que "Consum_mitja_L_100km" y "Km_anual" dependerá de "Te_cotxe".

In [ ]:
df.notnull().sum().sort_values(ascending=False)

ID                            989
Nom                           989
Cognoms                       989
DNI                           989
País d'origen                 989
Ciutat                        989
Dia de Naixement              989
Mes de Naixement              989
Any de Naixement              989
Salari mensual                989
Càrrec                        989
Grup Professional             989
Gènere                        950
Temperatura_mitjana_ciutat    922
Nombre_fills                  693
Te_cotxe                      645
No Fills                      574
Fills                         412
Km_anuals                     312
Consum_mitja_L_100km          258
dtype: int64

# Exercici 3: Transformacions necessàries i preparació del dataset

> Normalitzar els valors categòrics per evitar ambigüitats (per exemple, valors que representen el mateix concepte però estan escrits de manera diferent).

**Gènere**

Dejaremos 3 categorias:

*   'Dona'
*   'Home'
*   'Altres opcions'

In [ ]:
df['Gènere'].value_counts(dropna=False)

Gènere
D       318
H       274
Dona    118
F       107
Home     51
NaN      39
M        34
A        24
NC       23
??        1
Name: count, dtype: int64

In [ ]:
df['Gènere'] = df['Gènere'].replace({
    "D": "Dona", # dona
    "F" : "Dona", # feminino
    "H" : "Home", # home
    "M" : "Home", # masculino
    "A": "Altres opcions", # altre
    "NC": "Altres opcions", # no contesta
    "??": "Altres opcions"})
df['Gènere'].value_counts(dropna=False)

Gènere
Dona              543
Home              359
Altres opcions     48
NaN                39
Name: count, dtype: int64

In [ ]:
#comprobacion de la coherencia entre nombre y genero cogiendo 10 filas al azar
df[["Nom", "Gènere"]].sample(10)

         Nom Gènere
414    Oriol   Dona
297  Claudia   Dona
101      Pol   Dona
432    David   Home
710   Xavier   Home
796   Alexia   Home
806   Simone   Dona
592    Marta   Dona
483     Marc   Dona
905      Mia   Home

Observamos con frecuencia que un nombre considerado como masculino pertenene a una mujer y viceversa.
No actuaremos sobre ello pero es un punto a tener en consideracion.

**Salari mensual**

Revisamos primero que contiene la columna Salari mensual.
Vemos que tiene palabras, simbolos..

Crearemos une nueva columna, empezamos limpiando los espacios, comas, puntos, el simbolo € y la palabra 'euros'.

In [ ]:
df['Salari mensual'].isna().sum()

np.int64(0)

In [ ]:
df['Salari mensual'].sample(20)

463           1,701 €
285           1,250 €
496           1,438 €
826           1,441 €
799           2,170 €
880           1,495 €
725    mil vuit-cents
371           2,273 €
249             1813€
86            1,436 €
888         922 euros
658           1,238 €
589           1,429 €
12            3,672 €
383             971 €
30              2564€
88            1,890 €
920           1,054 €
957           1,042 €
971           2,852 €
Name: Salari mensual, dtype: object

In [ ]:
# 1. Creamos la nueva columna como una copia de la original
df['Salari mensual_euros'] = df['Salari mensual'].astype(str)

# 2. Definimos el patrón de limpieza (espacios, €, comas, puntos y la palabra 'euros')
patron_limpieza = r'[\s€,.]|euros'

# 3. Aplicamos la limpieza en la nueva columna
df['Salari mensual_euros'] = df['Salari mensual_euros'].str.replace(patron_limpieza, '', regex=True, case=False)

Despues de esta primera limpieza, comprobamos que valores nos quedan por contemplar

In [ ]:
# Filtramos las celdas que no son números tras la limpieza
filas_con_texto = df[~df['Salari mensual_euros'].str.isdigit()][['Salari mensual_euros']]

# Mostramos los valores únicos para ver qué palabras quedaron
print(list(filas_con_texto['Salari mensual_euros'].unique()))

['milvuit-cents', 'dosmil', 'n/d', 'tresmil', 'molts']

Cambiamos las palabras por numeros o por NaN segun el caso y aplicamos la conversion a tipo numerico

In [ ]:
# 4. Diccionario de correspondencia adaptado (sin espacios ni símbolos)
mapping = {
    'milvuit-cents': '1800',
    'dosmil': '2000',
    'tresmil': '3000',
    'molts': np.nan,
    'n/d': np.nan,
    'nan': np.nan
}

# 5. Reemplazamos el texto por los números correspondientes en la nueva columna
df['Salari mensual_euros'] = df['Salari mensual_euros'].replace(mapping)

# 6. Convertimos el resultado final a tipo numérico de forma definitiva
df['Salari mensual_euros'] = pd.to_numeric(df['Salari mensual_euros'], errors='coerce')

Comprobamos que la columna ya es de tipo decimal

In [ ]:
df['Salari mensual_euros'].dtype

dtype('float64')

**Te_cotxe, km_anuals, Consum_mitja_L_100km**

> Revisar la coherència dels valors nuls, assegurant que:
Les persones que tenen quilometratge anual i consum mitjà associats disposen de cotxe. En els casos en què consti consum mitjà però no quilometratge anual, caldrà decidir com resoldre aquesta incoherència de manera justificada.

Verificamos si existen filas donde 'Te_cotxe' es False, pero 'Km_anuals' o 'Consum_mitja_L_100km' no son nulos. Vemos que no se da el caso.

Y el supuesto inverso (donde 'Te_cotxe' es True pero 'Km_anuals' o 'Consum_mitja_L_100km' son nulos) podria ser real, imaginando que un empleado tenga vehiculo pero no lo use.

Si 'Consum_mitja_L_100km' es nulo pero 'Km_anuals' tiene dato, considero que la informacion es incompleta pero no inconsiste. Lo mantenemos tal cual. Aun asi revisaremos cuantas veces ocurren estos casos para tener más contexto.


En resumen:
- si 'Te_cotxe' = False, 'Km_anuals' y 'Consum_mitja_L_100km' deben ser NaN
- si 'Te_cotxe' =  True, 'Km_anuals' o 'Consum_mitja_L_100km' pueden tener valor o ser NaN

In [ ]:
# Verificamos si un empleado dice no tener coche, pero rellena 'Km_anuals' o 'Consum_mitja_L_100km'
df[(df['Te_cotxe'] == False) & (df['Km_anuals'] > 0 | df['Consum_mitja_L_100km'].notna())]

Empty DataFrame
Columns: [ID, Nom, Cognoms, DNI, País d'origen, Ciutat, Dia de Naixement, Mes de Naixement, Any de Naixement, Gènere, Salari mensual, Fills, No Fills, Grup Professional, Càrrec, Nombre_fills, Te_cotxe, Km_anuals, Consum_mitja_L_100km, Temperatura_mitjana_ciutat, Salari mensual_euros]
Index: []

[0 rows x 21 columns]

In [ ]:
# Buscamos cuantas veces se ha rellenado la columna Km_anuals dejando Consum_mitja_L_100km vacio
df[(df['Consum_mitja_L_100km']== 0) | (df['Consum_mitja_L_100km'].isna()) & (df['Km_anuals']> 0)].shape

(46, 21)

In [ ]:
df[(df['Te_cotxe'] == True)].shape

(325, 21)

In [ ]:
# Buscamos cuantas veces se ha rellenado unicamente la columna 'Consum_mitja_L_100km' dejando Km_anuals vacio
df[(df['Km_anuals']== 0) | (df['Km_anuals'].isna()) & (df['Consum_mitja_L_100km']> 0)].shape

(6, 21)

Numero de empleados que tienen coche y rellenan solo una de las dos columnas:

'Km_anuals' es superior a 0 y 'Consum_mitja_L_100km' es 0 o NaN
 - 46 filas (14.2%)

'Km_anuals'es 0 o NaN y 'Consum_mitja_L_100km' es superior a 0
- 6 filas (1.8%)

Revisamos 0 o NaN, porque un usuario suele confundir un valor = 0 con un valor nulo.

Sobre un total de 325 empleados que dice tener coche, que una de las dos columnas 'Km_anuals' o 'Consum_mitja_L_100km' sea 0 o NaN representa un 16%.

Aun así, no disponemos de criterio fiable para imputar los datos faltantes.

Para 'Km_anuals', no sabemos si se tratan de las distancias entre el domicilio y lugar de trabajo, que tipo de trayectos se realizan (de casa a la oficina, desplazamientos para visitar clientes...).

Para 'Consum_mitja_L_100km', influye el modelo del coche, la forma de conducir, si los trayectos se realizan por ciudad, afueras o autopista...

Estos datos dependen de muchas variables propios a cada empleado y careceria de sentido completar los datos faltantes basandose en los de otros empleados.

Por último, cambiamos el tipo de la columna 'Te_cotxe' a booleano para que sea más coherente con los datos que contiene.

In [ ]:
print(df['Te_cotxe'].value_counts(dropna=False))

Te_cotxe
NaN      344
True     325
False    320
Name: count, dtype: int64

In [ ]:
# Limpiamos el texto quitando espacios y convertimos a minúsculas
columna_limpia = df['Te_cotxe'].astype(str).str.strip().str.lower()

# Convertimos el texto a booleanos
mapa_booleanos = {'true': True, 'false': False}

df['Te_cotxe'] = columna_limpia.map(mapa_booleanos).astype("boolean")

In [ ]:
print(df['Te_cotxe'].dtype)

boolean

**Nombre_fills, Fills**

> Les persones que tenen un valor en el nombre de fills efectivament tenen fills.

Buscamos las filas en las que el numero de hijos informado es mayor que 0 pero la columna 'Fills' no informa True.

Modificamos 'Fills' a True en las 15 filas encontradas y comprobamos.

In [ ]:
# Buscamos las filas en las que el numero de hijos informado es mayor que 0 pero la columna 'Fills' no informa True.
df[(df['Nombre_fills'] > 0) & (df['Fills'] != True)]

Empty DataFrame
Columns: [ID, Nom, Cognoms, DNI, País d'origen, Ciutat, Dia de Naixement, Mes de Naixement, Any de Naixement, Gènere, Salari mensual, Fills, No Fills, Grup Professional, Càrrec, Nombre_fills, Te_cotxe, Km_anuals, Consum_mitja_L_100km, Temperatura_mitjana_ciutat, Salari mensual_euros]
Index: []

[0 rows x 21 columns]

In [ ]:
# Modificamos 'Fills' a True
df.loc[(df['Nombre_fills'] > 0) & (df['Fills'] != True),'Fills'] = True
df[(df['Nombre_fills'] > 0) & (df['Fills'] != True)]

Empty DataFrame
Columns: [ID, Nom, Cognoms, DNI, País d'origen, Ciutat, Dia de Naixement, Mes de Naixement, Any de Naixement, Gènere, Salari mensual, Fills, No Fills, Grup Professional, Càrrec, Nombre_fills, Te_cotxe, Km_anuals, Consum_mitja_L_100km, Temperatura_mitjana_ciutat, Salari mensual_euros]
Index: []

[0 rows x 21 columns]

> Unificar la informació sobre fills en una única columna, ja que mantenir diverses columnes amb informació complementària no és òptim i pot generar problemes analítics (redundància o multicolinealitat).

Unir las columnas 'Fills' y 'No Fills' es una opcion pero la columna 'Nombre_fills' ya nos indica si un empleado tiene hijos y ademas especifica cuantos.

Podemos descartar 'Fills' y 'No Fills' y usar unicamente la columna 'Nombre_fills'.

La convertimos a tipo int.

In [ ]:
df.drop(columns=['Fills', 'No Fills'], inplace=True)

In [ ]:
df['Nombre_fills'].value_counts(dropna=False)

Nombre_fills
0.0    301
NaN    296
1.0    171
2.0     79
4.0     77
3.0     64
5.0      1
Name: count, dtype: int64

**Temperatura**

> Validar la temperatura mitjana. En cas que aquesta informació falti, hauràs d'imputar-la utilitzant un criteri raonable (per ciutat o per un nivell superior justificat).

Se podria usar la moda, pero hay pocos valores unicos repetidos por ciudad (como maximo se repite la misma temperatura 4 veces, mientras podemos llegar a tener hasta 51 entradas para la misma ciudad), asi que no destaca ningun dato en particular, no es representativo.

Optamos por usar la mediana por ciudad, para evitar que los valores extremos distorsionen el resultado, cosa que pasaría con la media.

Revisamos la cantidad de NaN, son 67, y los reemplazamos por la mediana de la ciudad y comprobamos.

In [ ]:
# sacamos una descripcion general de las temperaturas agrupadas por ciudad para mayor contexto
df.groupby('Ciutat')['Temperatura_mitjana_ciutat'].agg([ "count", "mean", "median", "min", "max"])

                            count       mean  median   min   max
Ciutat
A Coruña                       43  12.897674   13.80  -5.0  19.3
Alacant                        39  17.384615   18.00 -10.0  42.0
Barcelona                      51  16.784314   16.60 -10.0  42.0
Bergen                         10   8.820000    7.85  -5.0  42.0
Berlin                          6   9.533333    9.85   7.6  11.1
Bilbao                         43  13.465116   14.10  -5.0  18.8
Bologna                        11  15.581818   13.30  10.8  38.0
Bordeaux                       10  11.530000   12.90  -5.0  16.2
Desconeguda                     0        NaN     NaN   NaN   NaN
Düsseldorf                      5   6.500000    9.20 -10.0  14.8
Firenze                        17  14.588235   14.30  -5.0  42.0
Frankfurt                       6  11.916667   10.85 -10.0  38.0
Genova                         12  17.425000   15.90  13.2  42.0
Girona                         39  13.269231   14.50  -5.0  19.4
Hamburg                         9   9.355556    8.90   4.6  15.0
Köln                            3   5.333333    9.50  -5.0  11.5
Las Palmas de Gran Canaria     43  20.674419   21.70 -10.0  38.0
Leipzig                         5  11.540000   12.50   9.1  13.7
Lille                          10  14.440000   12.05   9.4  38.0
Lyon                            4  10.700000   10.45   8.1  13.8
Madrid                         39  15.833333   15.40   8.6  42.0
Marseille                      12  14.950000   14.60  10.4  20.6
Milano                         13  13.400000   12.80  10.6  16.4
Murcia                         46  19.000000   18.85  14.1  42.0
Màlaga                         48  19.616667   18.95  12.6  38.0
München                         4   9.375000    8.70   8.0  12.1
Nantes                         12  12.166667   12.70   9.0  14.1
Napoli                         18  15.961111   15.70 -10.0  42.0
Nice                           11  16.363636   16.50  11.7  19.0
Oslo                           14   7.785714    7.10   4.8  10.6
Palma                          51  17.270588   18.00 -10.0  42.0
Paris                           7  12.471429   12.60  10.3  14.0
Roma                           15  14.173333   15.40 -10.0  19.9
Sevilla                        47  18.423404   19.20  -5.0  42.0
Stavanger                       8   7.762500    7.85   5.8   9.9
Stuttgart                       7  10.328571   10.20   7.0  13.1
Tarragona                      42  16.511905   16.80  -5.0  38.0
Torino                         15  17.353333   14.40  -5.0  42.0
Toulouse                       14  13.728571   13.65 -10.0  38.0
Tromsø                          4   2.725000    2.95   0.0   5.0
Trondheim                       6   4.383333    3.95   2.4   7.0
Valladolid                     43  13.411628   12.20  -5.0  42.0
València                       32  16.650000   17.30 -10.0  21.3
Venezia                         4  13.850000   14.20  11.5  15.5
Zaragoza                       44  15.338636   15.20 -10.0  42.0

In [ ]:
# revisamos los valores repetidos por ciudad
pd.set_option('display.max_rows', None)
print(df.groupby('Ciutat')['Temperatura_mitjana_ciutat'].value_counts())

Ciutat                      Temperatura_mitjana_ciutat
A Coruña                    -5.0                          3
                             12.9                         3
                             15.9                         3
                             11.9                         2
                             13.0                         2
                             13.9                         2
                             15.4                         2
                             15.5                         2
                             15.6                         2
                             10.0                         1
                             11.1                         1
                             11.3                         1
                             11.6                         1
                             11.7                         1
                             12.1                         1
                             12.5                         1
                             13.2                         1
                             13.3                         1
                             13.4                         1
                             13.7                         1
                             13.8                         1
                             14.0                         1
                             14.4                         1
                             14.8                         1
                             15.1                         1
                             16.2                         1
                             17.3                         1
                             17.4                         1
                             18.0                         1
                             18.4                         1
                             19.3                         1
Alacant                      19.4                         3
                            -10.0                         2
                             16.7                         2
                             17.4                         2
                             18.4                         2
                            -5.0                          1
                             14.4                         1
                             16.3                         1
                             16.5                         1
                             16.6                         1
                             16.8                         1
                             16.9                         1
                             17.0                         1
                             17.2                         1
                             17.3                         1
                             17.7                         1
                             17.8                         1
                             17.9                         1
                             18.0                         1
                             18.1                         1
                             18.2                         1
                             18.5                         1
                             18.7                         1
                             18.8                         1
                             18.9                         1
                             19.7                         1
                             20.1                         1
                             20.9                         1
                             21.4                         1
                             21.8                         1
                             24.3                         1
                             38.0                         1
                             42.0                         1
Barcelona                    14.2                         2
                             14.6                         2
                             14.7                         2
                             15.3                         2
                             15.4                         2
                             16.1                         2
                             16.7                         2
                             16.9                         2
                             17.1                         2
                             18.6                         2
                             38.0                         2
                            -10.0                         1
                            -5.0                          1
                             12.2                         1
                             13.2                         1
                             13.4                         1
                             13.5                         1
                             13.7                         1
                             14.3                         1
                             14.5                         1
                             14.8                         1
                             15.6                         1
                             15.7                         1
                             16.5                         1
                             16.6                         1
                             17.0                         1
                             17.3                         1
                             17.5                         1
                             17.6                         1
                             17.7                         1
                             18.0                         1
                             18.2                         1
                             18.4                         1
                             18.5                         1
                             18.7                         1
                             18.9                         1
                             20.1                         1
                             20.8                         1
                             21.1                         1
                             42.0                         1
Bergen                      -5.0                          2
                             5.5                          1
                             6.2                          1
                             6.9                          1
                             8.8                          1
                             9.1                          1
                             9.5                          1
                             10.2                         1
                             42.0                         1
Berlin                       10.7                         2
                             7.6                          1
                             8.1                          1
                             9.0                          1
                             11.1                         1
Bilbao                       10.3                         2
                             13.1                         2
                             13.5                         2
                             15.0                         2
                             16.3                         2
                            -5.0                          1
                             6.7                          1
                             9.9                          1
                             10.8                         1
                             10.9                         1
                             11.1                         1
                             11.5                         1
                             12.1                         1
                             12.2                         1
                             12.7                         1
                             12.8                         1
                             12.9                         1
                             13.0                         1
                             13.2                         1
                             13.3                         1
                             14.1                         1
                             14.2                         1
                             14.5                         1
                             14.7                         1
                             14.8                         1
                             14.9                         1
                             15.1                         1
                             15.2                         1
                             15.3                         1
                             15.4                         1
                             15.5                         1
                             15.6                         1
                             16.0                         1
                             16.6                         1
                             17.3                         1
                             18.2                         1
                             18.3                         1
                             18.8                         1
Bologna                      10.8                         1
                             11.9                         1
                             12.0                         1
                             12.1                         1
                             12.7                         1
                             13.3                         1
                             14.0                         1
                             15.0                         1
                             15.3                         1
                             16.3                         1
                             38.0                         1
Bordeaux                     15.2                         2
                            -5.0                          1
                             9.0                          1
                             12.3                         1
                             12.7                         1
                             12.8                         1
                             13.0                         1
                             13.9                         1
                             16.2                         1
Düsseldorf                  -10.0                         1
                             8.2                          1
                             9.2                          1
                             10.3                         1
                             14.8                         1
Firenze                      10.5                         2
                             16.6                         2
                            -5.0                          1
                             11.3                         1
                             11.7                         1
                             12.8                         1
                             13.9                         1
                             14.1                         1
                             14.3                         1
                             15.0                         1
                             15.6                         1
                             15.7                         1
                             16.1                         1
                             16.3                         1
                             42.0                         1
Frankfurt                   -10.0                         1
                             9.2                          1
                             10.2                         1
                             11.5                         1
                             12.6                         1
                             38.0                         1
Genova                       15.9                         3
                             13.2                         2
                             13.5                         1
                             14.0                         1
                             15.2                         1
                             16.1                         1
                             16.5                         1
                             17.7                         1
                             42.0                         1
Girona                       14.8                         4
                             12.9                         3
                            -5.0                          2
                             13.1                         2
                             14.9                         2
                             16.1                         2
                             16.5                         2
                             18.1                         2
                             8.1                          1
                             9.5                          1
                             10.2                         1
                             11.3                         1
                             11.6                         1
                             11.7                         1
                             12.2                         1
                             13.2                         1
                             13.3                         1
                             13.6                         1
                             13.8                         1
                             14.2                         1
                             14.5                         1
                             15.2                         1
                             15.3                         1
                             15.6                         1
                             16.0                         1
                             16.3                         1
                             17.2                         1
                             19.4                         1
Hamburg                      4.6                          1
                             6.4                          1
                             6.6                          1
                             8.7                          1
                             8.9                          1
                             9.4                          1
                             9.9                          1
                             14.7                         1
                             15.0                         1
Köln                        -5.0                          1
                             9.5                          1
                             11.5                         1
Las Palmas de Gran Canaria   18.4                         2
                             19.8                         2
                             20.0                         2
                             21.7                         2
                             21.9                         2
                             22.0                         2
                             22.7                         2
                            -10.0                         1
                            -5.0                          1
                             18.8                         1
                             19.3                         1
                             19.9                         1
                             20.1                         1
                             20.3                         1
                             20.6                         1
                             20.7                         1
                             20.8                         1
                             20.9                         1
                             21.0                         1
                             21.2                         1
                             21.3                         1
                             21.5                         1
                             21.8                         1
                             22.1                         1
                             22.3                         1
                             22.4                         1
                             23.2                         1
                             23.4                         1
                             23.5                         1
                             23.7                         1
                             24.0                         1
                             24.4                         1
                             25.1                         1
                             25.2                         1
                             25.5                         1
                             38.0                         1
Leipzig                      12.5                         2
                             9.1                          1
                             9.9                          1
                             13.7                         1
Lille                        9.4                          1
                             9.8                          1
                             11.3                         1
                             11.9                         1
                             12.0                         1
                             12.1                         1
                             12.4                         1
                             12.9                         1
                             14.6                         1
                             38.0                         1
Lyon                         8.1                          1
                             8.4                          1
                             12.5                         1
                             13.8                         1
Madrid                       15.0                         3
                             15.7                         3
                             14.4                         2
                             14.8                         2
                             15.4                         2
                             16.1                         2
                             8.6                          1
                             11.4                         1
                             11.6                         1
                             12.1                         1
                             12.3                         1
                             12.9                         1
                             13.2                         1
                             13.5                         1
                             13.6                         1
                             13.9                         1
                             14.9                         1
                             15.3                         1
                             15.6                         1
                             15.9                         1
                             16.5                         1
                             16.8                         1
                             16.9                         1
                             17.0                         1
                             17.8                         1
                             18.0                         1
                             18.1                         1

In [ ]:
# revisamos los valores nulos
df['Temperatura_mitjana_ciutat'].isna().sum()

np.int64(67)

In [ ]:
df['Temperatura_mitjana_ciutat'] = df['Temperatura_mitjana_ciutat'].fillna(df.groupby('Ciutat')['Temperatura_mitjana_ciutat'].transform('median'))

In [ ]:
# Comprobamos que no quedan filas sin temperatura, salvo en esta fila 1006, dado que la ciudad no es real y no se ha podido sacar la mediana.
df[df['Temperatura_mitjana_ciutat'].isna()]

,ID,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Grup Professional,Càrrec,Nombre_fills,Te_cotxe,Km_anuals,Consum_mitja_L_100km,Temperatura_mitjana_ciutat,Salari mensual_euros
1006,1006,???,###,XXXX,Narnia,Desconeguda,-99.0,99.0,3000.0,Altres opcions,molts,Z,???,NaN,<NA>,NaN,NaN,NaN,NaN

**Salari mensual_euros**

> Revisar i imputar els salaris faltants, aplicant criteris analítics coherents (com ara càrrec, grup professional, ciutat, gènere o franja d'edat).

1) unificaremos los cargos de trabajo, de 13, conservamos 8 puestos.

*   'Administratiu' (incluye 'Admin.')
*   'Cap de projecte' (incluye 'Cap de Projecte', estandararizamos a una mayúscula inicial)
*   'Data analyst' (incluye 'Data Analyst', estandarizamos a una mayúscula inicial e incluye 'Analista' y 'Analyst')
*   'Junior analyst' (se pasa 'Analista junior' a ingles para mayor coherencia con 'Data analyst' y 'Senior analyst')
*   'Project lead'
*   'Responsable de vendes'
*   'Senior analyst'
*   'Tècnic IT'

Realizamos las modificaciones y comprobamos.

2) Para imputar los salarios faltantes, en este caso tambien usaremos la mediana y haremos la mediana por cargo y por grupo profesional.

In [ ]:
# ordenamos los valores unicos de la columna "Càrrec"
df["Càrrec"].dropna().sort_values().unique()

array(['???', 'Admin.', 'Administratiu', 'Analista', 'Analista junior',
       'Analyst', 'Cap de Projecte', 'Cap de projecte', 'Data Analyst',
       'Data analyst', 'Project lead', 'Responsable de vendes',
       'Senior analyst', 'Tècnic IT'], dtype=object)

In [ ]:
# sacamos una descripcion general de las salarios agrupados por cargo para mayor contexto antes de unificar los cargos
df.groupby('Càrrec')['Salari mensual_euros'].agg([ "count", "mean", "median", "min", "max"])

                       count         mean  median     min     max
Càrrec
???                        0          NaN     NaN     NaN     NaN
Admin.                     6  1822.333333  1627.5  1234.0  3275.0
Administratiu            102  1441.852941  1270.0   673.0  3087.0
Analista                 112  1452.241071  1325.5   701.0  3128.0
Analista junior          105  1344.323810  1219.0   726.0  3000.0
Analyst                    9  1601.000000  1682.0   889.0  2426.0
Cap de Projecte           11  1165.545455  1083.0   722.0  1968.0
Cap de projecte           92  1910.369565  1803.5   919.0  3672.0
Data Analyst             137  1548.087591  1430.0   743.0  3615.0
Data analyst              17  1684.176471  1517.0   778.0  2852.0
Project lead              17  1455.823529  1244.0   847.0  2534.0
Responsable de vendes    122  1548.319672  1330.0   723.0  3437.0
Senior analyst           118  1781.932203  1553.5   889.0  3672.0
Tècnic IT                126  1560.714286  1397.0   746.0  3610.0

In [ ]:
df['Càrrec'] = df['Càrrec'].replace({
    "Admin.": "Administratiu",
    "Analyst" : "Data analyst",
    "Analista" : "Data analyst",
    "Cap de Projecte" : "Cap de projecte",
    "Data Analyst" : "Data analyst",
    "Analista junior" : "Junior analyst"})
sorted(df['Càrrec'].unique())

['???',
 'Administratiu',
 'Cap de projecte',
 'Data analyst',
 'Junior analyst',
 'Project lead',
 'Responsable de vendes',
 'Senior analyst',
 'Tècnic IT']

In [ ]:
# sacamos una nueva descripcion general de las salarios con los cargos unificados y agrupado tambien por "Grup Professional"
df.groupby(["Grup Professional", "Càrrec"])["Salari mensual_euros"].agg([ "count", "mean", "median", "min", "max"])

                                         count         mean  median     min  \
Grup Professional Càrrec
Grup A            Administratiu             47   993.957447   997.0   673.0
                  Cap de projecte           39  1227.051282  1258.0   722.0
                  Data analyst             120  1060.300000  1022.5   701.0
                  Junior analyst            58  1031.017241   983.5   726.0
                  Project lead               8  1069.750000  1032.5   847.0
                  Responsable de vendes     60  1089.500000  1042.5   723.0
                  Senior analyst            55  1313.709091  1242.0   889.0
                  Tècnic IT                 61  1153.737705  1099.0   746.0
Grup B            Administratiu             38  1515.736842  1513.5  1090.0
                  Cap de projecte           42  1879.595238  1953.0  1350.0
                  Data analyst             102  1591.598039  1573.5  1056.0
                  Junior analyst            34  1527.470588  1519.0  1079.0
                  Project lead               7  1600.142857  1546.0  1207.0
                  Responsable de vendes     40  1663.650000  1643.0  1303.0
                  Senior analyst            44  1841.113636  1829.0  1385.0
                  Tècnic IT                 42  1582.595238  1597.0  1198.0
Grup C            Administratiu             19  2215.105263  2180.0  1739.0
                  Cap de projecte           18  2652.444444  2702.0  1663.0
                  Data analyst              43  2268.790698  2225.0  1771.0
                  Junior analyst            11  2174.090909  2245.0  1732.0
                  Project lead               2  2495.000000  2495.0  2456.0
                  Responsable de vendes     16  2411.125000  2399.0  1923.0
                  Senior analyst            13  2743.153846  2759.0  2000.0
                  Tècnic IT                 15  2311.066667  2191.0  1939.0
Grup D            Administratiu              4  2900.500000  2951.0  2613.0
                  Cap de projecte            4  3508.250000  3511.5  3338.0
                  Data analyst              10  3064.200000  3098.0  2458.0
                  Junior analyst             2  2753.000000  2753.0  2634.0
                  Responsable de vendes      6  3066.833333  3010.5  2627.0
                  Senior analyst             6  3557.333333  3582.0  3284.0
                  Tècnic IT                  8  3142.125000  3089.0  2746.0
Z                 ???                        0          NaN     NaN     NaN

                                            max
Grup Professional Càrrec
Grup A            Administratiu          1385.0
                  Cap de projecte        1595.0
                  Data analyst           3000.0
                  Junior analyst         3000.0
                  Project lead           1469.0
                  Responsable de vendes  2000.0
                  Senior analyst         3000.0
                  Tècnic IT              3000.0
Grup B            Administratiu          2000.0
                  Cap de projecte        2419.0
                  Data analyst           2147.0
                  Junior analyst         1893.0
                  Project lead           2273.0
                  Responsable de vendes  2100.0
                  Senior analyst         2397.0
                  Tècnic IT              2125.0
Grup C            Administratiu          3275.0
                  Cap de projecte        3070.0
                  Data analyst           2852.0
                  Junior analyst         2516.0
                  Project lead           2534.0
                  Responsable de vendes  2855.0
                  Senior analyst         3203.0
                  Tècnic IT              2810.0
Grup D            Administratiu          3087.0
                  Cap de projecte        3672.0
                  Data analyst           3615.0
                  Junior analyst         2872.0
                  Responsable de vendes  3437.0
                  Senior analyst         3672.0
                  Tècnic IT              3610.0
Z                 ???                       NaN

In [ ]:
# revisamos los valores nulos
df['Salari mensual_euros'].isna().sum()

np.int64(15)

In [ ]:
df['Salari mensual_euros'] = df['Salari mensual_euros'].fillna(df.groupby(["Grup Professional", "Càrrec"])["Salari mensual_euros"].transform('median'))

In [ ]:
# Comprobamos que no quedan filas sin salario. Queda la misma fila 1006.
df[df['Salari mensual_euros'].isna()]

,ID,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Grup Professional,Càrrec,Nombre_fills,Te_cotxe,Km_anuals,Consum_mitja_L_100km,Temperatura_mitjana_ciutat,Salari mensual_euros
1006,1006,???,###,XXXX,Narnia,Desconeguda,-99.0,99.0,3000.0,Altres opcions,molts,Z,???,NaN,<NA>,NaN,NaN,NaN,NaN

De hecho, eliminamos ya esta fila porque ademas de no aportar datos verdaderos, no hace mas que distortionar los analisis con outliers.

In [ ]:
df[df["País d'origen"] == "Narnia"]

,ID,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Grup Professional,Càrrec,Nombre_fills,Te_cotxe,Km_anuals,Consum_mitja_L_100km,Temperatura_mitjana_ciutat,Salari mensual_euros
1006,1006,???,###,XXXX,Narnia,Desconeguda,-99.0,99.0,3000.0,Altres opcions,molts,Z,???,NaN,<NA>,NaN,NaN,NaN,NaN

In [ ]:
df.drop(index=1006,inplace=True)

In [ ]:
df[df["País d'origen"] == "Narnia"]

Empty DataFrame
Columns: [ID, Nom, Cognoms, DNI, País d'origen, Ciutat, Dia de Naixement, Mes de Naixement, Any de Naixement, Gènere, Salari mensual, Grup Professional, Càrrec, Nombre_fills, Te_cotxe, Km_anuals, Consum_mitja_L_100km, Temperatura_mitjana_ciutat, Salari mensual_euros]
Index: []

**Dia de Naixement, Mes de Naixement, Any de Naixement**

Estas columnas solo pueden numeros enteros, asi que las convertimos a int

Pasaremos a NaN los valores fuera de rango:

  * día de nacimiento: el rango de dias es de 1 a 31
  * mes de nacimiento: el rango de meses es de 1 a 12
  * año de nacimiento: min 1940 y max 2010 (siendo 16 años la edad minima para trabajar)

In [ ]:
df['Dia de Naixement'].astype('Int64')
df['Mes de Naixement'].astype('Int64')
df['Any de Naixement'].astype('Int64')

0       1958
1       1960
2       1961
3       1985
4       1965
5       1978
6       1971
7       1962
8       1963
9       1940
10      1961
11      1974
12      1973
13      1961
14      1980
15      1960
16      2004
17      1964
18      1978
19      2002
20      1993
21      1972
22      1982
23      1974
24      1973
26      1973
27      1973
28      1987
29      1992
30      1994
31      1987
32      1965
33      1987
34      1993
35      1961
37      1967
38      1990
39      3000
40      1992
41      2019
42      1976
43      1976
44      2001
45      1997
46      1984
47      3000
48      1958
49      1977
50      1964
51      1964
52      1988
53      2019
54      1961
55      1974
56      1984
57      1962
58      1994
59      1995
60      1981
61      1983
62      1976
63      1978
64      1988
65      2003
66      1997
67      2019
68      1962
69      1983
70      1960
71      2019
72      1940
73      1940
74      1991
75      1965
76      2000
77      1977
78      1973
79      1989
80      1981
81      2019
82      2000
83      1967
84      1982
85      2004
86      1992
87      1988
88      1994
90      2001
91      1973
92      1990
93      2026
94      1966
95      1959
96      2000
97      1969
98      1975
99      1973
100     1972
101     2004
102     1990
103     1997
105     1982
106     1986
107     1975
108     1993
109     1958
110     1983
111     1982
112     1999
113     2002
115     1975
116     1969
117     1999
118     1992
119     1965
120     1984
121     1983
122     1978
123     1975
124     1987
125     1971
126     1983
127     1971
128     1940
129     1980
130     2001
131     1972
132     1958
133     1940
134     1974
135     2002
136     1983
137     1971
138     1982
139     1961
140     1960
141     1964
143     1979
144     1988
145     1985
146     2000
147     1986
148     1988
149     1996
150     1964
151     1988
152     1991
153     1973
154     2001
155     1975
156     1975
157     1995
158     1972
159     1982
160     1963
161     1962
162     1959
163     2000
164     1989
165     1961
166     1982
167     2004
168     1997
169     1973
170     2000
171     1993
172     1995
173     1996
174     1940
175     3000
176     1993
177     1986
178     1987
179     1990
180     1973
181     1989
182     1963
183     1976
184     1958
185     1974
186     1977
187     1980
188     1995
189     2000
190     1981
191     1982
192     1971
193     1963
194     1982
195     1996
196     1963
197     3000
198     1993
199     1996
200     2026
201     3000
202     1987
203     1993
204     2000
205     1992
206     1971
207     1984
208     2001
209     1983
210     2026
211     1998
212     1963
213     1996
214     1970
215     1984
216     1982
217     1981
218     2026
219     1987
220     1973
221     1994
222     1975
223     1998
224     1998
225     1977
226     1971
227     1977
228     1988
229     1978
230     1958
231     1960
232     1999
233     1959
234     1998
235     1966
236     1975
237     1975
238     1960
239     1999
240     1965
241     1969
242     1993
243     1976
244     1969
245     1997
246     1979
247     1988
248     1968
249     1986
251     1992
252     1995
253     1987
254     1992
255     2000
256     1998
257     1963
258     1978
259     1989
260     1973
261     1995
262     1968
263     1967
264     1980
265     1982
266     1969
267     1971
268     2019
269     1971
270     1962
271     1998
272     2001
273     1995
274     1940
275     1989
276     1980
277     3000
278     1973
279     1985
280     1998
282     1987
283     2002
284     1965
285     2001
286     1999
287     1974
288     1980
289     1967
290     1965
291     1977
292     1982
293     1959
294     2026
295     1998
296     1968
297     1977
298     1961
299     2003
300     1990
301     1985
302     1996
303     1974
304     1970
305     1985
306     1995
307     1994
308     1998
309     1962
310     1989
311     1973
312     1963
313     1991
314     1992
315     1982
316     1991
317     1969
318     1966
319     1994
320     1984
321     1980
322     2004
323     1967
324     1965
325     2019
326     1976
327     1996
328     1999
329     1990
330     1969
331     1997
332     1967
333     1997
334     2001
335     1959
336     1961
337     1999
338     1991
339     1961
340     1967
341     1991
342     1973
343     1964
344     3000
345     1976
346     1958
347     1986
348     1993
349     1963
350     1984
351     1982
352     1963
353     1982
354     2001
355     2002
356     1987
357     1989
358     2001
359     1984
360     1988
361     1964
362     1979
363     1961
364     2001
365     1962
366     1959
367     1970
368     1990
369     1995
370     1997
371     2026
373     1978
374     1983
375     1964
376     1968
377     1975
378     2003
379     1981
380     1958
381     1958
382     1996
383     1964
384     1989
385     1995
386     1959
387     1973
388     1987
389     1963
390     2019
391     1985
392     1982
393     1967
394     1969
395     1959
396     1979
397     2000
398     3000
399     1963
400     2026
401     1958
402     1976
403     1979
404     1983
405     1966
406     1983
407     1971
408     1991
409     1992
410     2000
411     1987
412     1985
413     1965
414     2003
415     3000
416     2026
417     2001
418     1980
419     1975
420     1989
421     1963
422     1997
423     1960
424     1999
425     1977
426     1975
427     1969
428     1999
429     1995
430     1994
431     1963
432     1960
433     1940
434     1962
435     1998
436     2026
437     1985
438     1976
439     1966
440     1987
441     1960
442     1967
443     1985
444     1974
445     1974
446     2004
447     1985
448     1985
449     2004
450     1995
451     2002
452     1982
453     1965
454     1973
455     1985
456     2004
457     1964
458     1968
459     2019
460     1977
461     1984
462     1993
463     1989
464     1969
465     1999
466     1982
467     2004
468     1978
469     2026
470     1985
471     1983
472     1979
473     1972
474     1972
475     1986
476     1980
477     1958
478     1974
479     1982
480     1981
481     1982
482     1973
483     1998
484     1967
485     1980
486     1940
487     1969
488     1985
489     1994
490     1976
491     1993
492     1977
493     1980
494     1983
495     1961
496     1960
497     1980
498     1974
499     1958
500     3000
501     1961
502     1978
503     2004
504     1980
505     1995
506     2003
507     1995
508     1995
509     1969
510     1971
511     1963
512     2019
513     1940
514     1976
515     1991
516     1968
517     1983
518     2002
519     1995
520     2002
521     1998
522     1979
523     1964
524     2019
525     1969
526     2019
527     1996
528     1990
529     1993
530     1981
531     1988
532     1986
533     1990
534     2002
535     1984
536     1994
537     1978
538     1973
539     1968
540     1977
541     1966
542     1958
543     1964
544     1990
545     1961
546     1963
547     1979
548     1990
549     1997
550     1960
551     1976
552     1981
553     1999
554     1982
555     2026
556     2004
557     1988
559     1980
560     1970
561     1994
562     1966
563     1996
564     1969
565     3000
566     1968
567     1983
568     1993
569     1973
570     1974
571     1965
572     1993
573     1987
574     1970
575     1959
576     1980
577     1982
578     1940
579     1972
580     1994
581     2019
582     1994
583     2001
584     1940
585     1940
586     3000
587     1970
588     1965
589     1981
590     1985
591     1999
592     1973
593     1997
594     2002
595     1976
596     1993
597     1980
598     1993
599     1989
600     1996
601     1969
602     1978
603     1965
604     1958
605     1982
606     1980
607     1979
608     1984
609     1992
610     1962
611     2019
612     1968
613     1965
614     1967
615     1998
616     1987
617     2001
618     1980
619     1984
620     1995
621     1998
622     1985
623     1985
624     1962
625     1998
626     2001
627     1968
628     1962
629     1983
630     1995
631     2000
632     1979
633     1994
634     1967
635     1965
636     1978
637     1978
638     1983
639     1972
640     1995
641     1986
642     1981
643     2000
644     1959
645     2002
646     2026
647     2003
648     1998
649     1979
650     1977
651     1963
652     1940
653     1986
655     1968
656     1966
657     1983
658     2000
659     2000
660     1993
661     2002
662     1977
663     1969
664     3000
665     1962
666     1993
667     1982
668     1986
669     1999
670     1968
671     1968
672     1959
673     1982
674     1978
675     1966
676     1962
677     1976
678     1977
679     1979
680     1990
681     2000
682     1968
683     2019
684     1968
685     1977
686     2019
687     1968
688     1990
689     1976
690     1995
691     2000
692     1981
693     1990
694     1985
695     1978
696     1965
697     3000
698     1992
699     1981
700     1970
701     1984
702     2004
703     1991
704     1971
705     1966
706     1976
707     1998
708     1962
709     1998
710     1968
711     2003
712     1972
713     1959
714     1966
715     1960
716     1960
717     1961
718     1962
719     1967
720     1993
721     1999
722     2003
723     1983
724     1981
725     1967
726     2004
727     1964
728     2001
729     2004
731     1959
732     1997
733     1996
734     2000
735     1994
736     1971
737     1966
738     1964
739     1996
740     1998
741     1984
742     1978
743     1980
744     1964
745     1978
746     2002
747     1998
748     2026
749     1979
750     1992
751     2026
752     1960
753     1979
755     1982
756     1970
759     1968
760     1972
761     1997
762     1969
763     1971
764     2019
765     1969
766     1993
767     1959
768     1991
769     2001
770     1960
771     2019
772     1965
773     1964
774     1977
775     1982
776     1962
777     1972
778     3000
779     1960
780     2004
781     1991
782     1986
783     1961
784     1969
785     1993
786     1996
787     1968
788     2019
789     1959
790     1965
791     1987
792     1986
793     2002
794     1971
795     1989
796     1962
797     1974
798     1965
799     2003
800     1982
801     1978
802     1996
803     2003
804     1980
805     1979
806     1975
807     1997
808     1973
809     1962
810     1996
811     1964
812     3000
813     1990
814     1975
815     1985
816     1993
817     1994
818     2002
819     1982
820     1993
821     1961
822     1966
823     2026
824     1977
825     1940
826     2004
827     1993
828     1960
829     1961
830     2002
831     1966
832     1960
833     1979
834     1988
835     2019
836     1958
837     3000
838     1966
839     1965
840     2002
841     1969
842     2002
843     1972
844     3000
845     1962
846     1960
847     1972
848     1979
849     1982
850     2000
851     1975
852     1969
853     1987
854     1977
855     1965
856     1959
857     1981
858     1983
859     1998
860     1972
861     1984
862     1978
863     1980
864     1977
865     1960
866     1971
867     2003
868     1994
869     1995
870     1984
871     1982
872     1969
873     1983
874     1996
875     2004
876     1981
877     1983
878     2002
879     1999
880     1995
881     1975
882     1962
883     1995
884     1961
885     1998
886     1940
887     1989
888     1967
889     1986
890     1969
891     1968
892     1999
893     1960
894     2019
895     1998
896     1967
897     1994
898     1993
899     1993
900     1990
901     2026
902     1998
903     1977
904     1985
905     1959
906     1976
907     1958
908     1979
909     2001
910     1999
911     3000
912     1996
914     2026
915     2001
916     1986
917     1971
918     2002
919     1988
920     1997
921     1990
922     1967
923     1968
924     1997
925     1992
926     2019
927     1983
928     1992
929     2001
930     1962
931     1966
932     1994
933     1966
934     1989
935     1959
936     1995
937     1995
938     1984
939     2004
940     1986
941     1968
942     1995
943     1963
944     1968
945     1975
946     1991
947     2004
948     1958
949     1995
950     1995
951     1977
952     1964
953     2002
954     1962
955     1967
956     2004
957     1973
958     2019
959     1977
960     1980
961     2000
962     1959
963     1991
964     1961
965     1980
966     1959
967     1970
968     1981
969     1988
970     1999
971     1964
972     1995
973     1998
974     1981
975     1987
976     2003
977     1991
978     1990
979     2004
980     1997
981     2026
982     1975
983     1996
984     1986
985     1977
986     1970
987     1971
988     1975
989     1969
990     1990
991     2002
992     1996
993     1960
994     1990
995     1993
996     1940
997     1961
998     1958
999     1991
1001    1996
1002    1983
1003    1981
1004    1973
Name: Any de Naixement, dtype: Int64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 988 entries, 0 to 1004
Data columns (total 19 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   ID                          988 non-null    int64
 1   Nom                         988 non-null    object
 2   Cognoms                     988 non-null    object
 3   DNI                         988 non-null    object
 4   País d'origen               988 non-null    object
 5   Ciutat                      988 non-null    object
 6   Dia de Naixement            988 non-null    float64
 7   Mes de Naixement            988 non-null    float64
 8   Any de Naixement            988 non-null    float64
 9   Gènere                      949 non-null    object
 10  Salari mensual              988 non-null    object
 11  Grup Professional           988 non-null    object
 12  Càrrec                      988 non-null    object
 13  Nombre_fills                693 non-null    float64
 14  Te_cotxe                    645 non-null    boolean
 15  Km_anuals                   312 non-null    float64
 16  Consum_mitja_L_100km        258 non-null    float64
 17  Temperatura_mitjana_ciutat  988 non-null    float64
 18  Salari mensual_euros        988 non-null    float64
dtypes: boolean(1), float64(8), int64(1), object(9)
memory usage: 148.6+ KB

In [ ]:
# contamos las celdas cuyos valores estan fuera de rango
df[(df["Dia de Naixement"] <1) | (df["Dia de Naixement"]>31)].shape

(0, 19)

In [ ]:
df[(df["Mes de Naixement"] <1) | (df["Mes de Naixement"]>12)].shape

(0, 19)

In [ ]:
df[(df["Any de Naixement"] <1940) | (df["Any de Naixement"]>2010)].shape

(0, 19)

In [ ]:
# reemplazamos por NaN los valores que estan fuera de rango
import numpy as np
df['Dia de Naixement'] = df['Dia de Naixement'].where(df['Dia de Naixement'].between(1, 31), np.nan)
df['Mes de Naixement'] = df['Mes de Naixement'].where(df['Mes de Naixement'].between(1, 12), np.nan)
df['Any de Naixement'] = df['Any de Naixement'].where(df['Any de Naixement'].between(1940, 2010), np.nan)

In [ ]:
# comprobamos que ya no queden años fuera de rango
df[(df["Any de Naixement"] < 1940) | (df["Any de Naixement"] > 2010)].shape

(0, 19)

In [ ]:
# comprobamos que ya no queden dias fuera de rango
df["Dia de Naixement"].sort_values().unique()

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
       27., 28., 29., 30., 31., nan])

In [ ]:
# comprobamos que ya no queden meses fuera de rango
df["Mes de Naixement"].sort_values().unique()

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., nan])

In [ ]:
anys_nuls = len(df["Any de Naixement"]) - df["Any de Naixement"].count()
mesos_nuls = len(df["Mes de Naixement"]) - df["Mes de Naixement"].count()
dies_nuls = len(df["Dia de Naixement"]) - df["Dia de Naixement"].count()
print(f"Cantidad de filas vacías: Any de Naixement: {anys_nuls}, Mes de Naixement: {mesos_nuls}, Dia de Naixement: {dies_nuls}")

Cantidad de filas vacías: Any de Naixement: 60, Mes de Naixement: 77, Dia de Naixement: 77

In [ ]:
df[["Any de Naixement", "Mes de Naixement", "Dia de Naixement"]].count()

Any de Naixement    928
Mes de Naixement    911
Dia de Naixement    911
dtype: int64

In [ ]:
df[
    df[['Dia de Naixement',
         'Mes de Naixement',
         'Any de Naixement']]
    .isna()
    .any(axis=1)
].shape[0]

77

Quedan:

dia 77 NaN / 911 validos / total 988

mes 77 NaN / 911 validos / total 988

any 60 NaN / 928 validos / total 988

filas donde falta día, mes o año : 77

# Exercici 4: Primeres anàlisis descriptives

>  Construir taules resum descriptives de salaris com una taula resum que permeti veure el sou mig, medià, mínim i màxim per Gènere. Ordena la taula en funció del sou mig.

In [ ]:
# F1 Calculamos la media, mediana, mínimo y máximo del salario por género, redondeando a dos decimales y ordenando por la media de forma descendente.
df.groupby('Gènere').agg({'Salari mensual_euros': ['mean', 'median', 'min', 'max']}).round(2).sort_values(by=('Salari mensual_euros', 'mean'), ascending=False)

               Salari mensual_euros
                               mean  median    min     max
Gènere
Home                        1697.27  1510.0  726.0  3672.0
Altres opcions              1658.98  1281.0  673.0  3600.0
Dona                        1481.74  1343.0  701.0  3564.0

> Crear una taula resum amb el salari mig per gènere (files) i país d'origen (columnes). Afegeix-hi les mitjanes als marges de la taula. Aplica format condicional a la taula per veure en un color més intens els valors més elevats.

In [ ]:
# F2 Calculamos la mediana de salario por género agrupado por pais
per_genere = df.pivot_table(
    index='Gènere',
    columns = "País d'origen",
    values = 'Salari mensual_euros',
    aggfunc = 'mean',
    margins=True,
    margins_name='Mitjana'
    ).round(2)

#Valores de estilo para la tabla.

per_genere_style = (
    per_genere
    .style
    .format("{:.2f}")
    .background_gradient(cmap='Blues')
)

display(per_genere_style)

> EXTRA

> Podries repetir l’anàlisi utilitzant percentatges i ràtios salarials, i comparar com canvia la interpretació respecte als valors absoluts?

In [ ]:
# F3 Proporcion de empleados por genero
per_genere_pct = df.pivot_table(
    index='Gènere',
    columns="País d'origen",
    values='Salari mensual_euros',
    aggfunc='count',
    margins=True,
    margins_name='Total'
)

per_genere_pct = (
    per_genere_pct
    .div(per_genere_pct.loc['Total'], axis=1)
    .mul(100)
    .round(2)
)

per_genere_style = (
    per_genere_pct
    .style
    .format("{:.2f}%")
    .background_gradient(cmap='Blues', axis=0)
)

display(per_genere_style)

In [ ]:
#F4 Calculamos la mediana de salario por género agrupado por pais, pero esta vez con ratios. El valor de referencia es el salario medio global, o sea 1551,72€ en valores absolutos.
media_global = df['Salari mensual_euros'].mean()
ratios = (per_genere / media_global)

display(ratios.style.background_gradient(cmap='Blues').format("{:.2f}"))

**valores absolutos**

F1. Resalta que los hombres ganan 223,27 € más de media que las mujeres.

F2. Excepto en Noruega, las mujeres siempre cobran menos de la media

**porcentajes**

F3. Usar porcentajes nos permite apreciar el tamaño de cada grupo y asi poner en perspectiva los resultados tanto en valores absolutos como en ratios.

**ratios**

F4. Conociendo la proporcion de cada grupo gracias a los porcentajes, destaca que, aunque siendo el grupo más grande con 57,35%, las mujeres tienen el salario medio más bajo, mientras que los hombres, siendo más pequeño, presentan el salario medio más alto.

Este rasgo es aun más presente en Alemania, donde las mujeres representan 73,33% de los empleados, con un ratio de salario de 0,92 (8% por debajo de la media) respecto a la media global, cuando los hombres representan 24,44% con un ratio de 1,24 (24% por encima de la media). Es el país donde se observa mayor diferencia, 32% de brecha. Italia al contrario, es donde los salarios entre generos están mas igualados, 12% de brecha.

# Nivell 2 - Anàlisi amb dades enriquides i estructures múltiples

# Exercici 1: Enriquiment mitjançant datasets externs

> Integrar el dataset principal amb el dataset contextual de ciutats.

In [ ]:
ciutats = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/ciutats_context.csv', encoding='cp1252')

In [ ]:
ciutats

,Ciutat,País,Cost_vida_index,Transport_public_score,Clima_tipus
0,Barcelona,Espanya,78,8.5,Mediterrani
1,Madrid,Espanya,75,8.0,Continental
2,València,Espanya,70,7.5,Mediterrani
3,Sevilla,Espanya,65,7.0,Mediterrani
4,Bilbao,Espanya,72,7.8,Oceànic
5,Zaragoza,Espanya,68,7.0,Continental
6,Murcia,Espanya,60,6.5,Mediterrani
7,Palma,Espanya,73,7.2,Mediterrani
8,Girona,Espanya,66,6.8,Mediterrani
9,Tarragona,Espanya,67,6.9,Mediterrani
10,A Coru\u00f1a,Espanya,69,7.1,Oceànic
11,Valladolid,Espanya,64,6.7,Continental
12,Alacant,Espanya,68,7.0,Mediterrani
13,Las Palmas de Gran Canaria,Espanya,62,6.8,Subtropical
14,Paris,França,85,9.0,Oceànic
15,Marseille,França,72,7.4,Mediterrani
16,Lyon,França,74,7.6,Continental
17,Bordeaux,França,73,7.2,Oceànic
18,Lille,França,71,7.3,Continental
19,Milano,Itàlia,80,7.5,Continental
20,Roma,Itàlia,78,7.6,Mediterrani
21,Torino,Itàlia,74,7.2,Continental
22,Genova,Itàlia,72,6.9,Mediterrani
23,Venezia,Itàlia,79,7.0,Mediterrani
24,Napoli,Itàlia,65,6.5,Mediterrani
25,Firenze,Itàlia,77,7.1,Continental
26,Berlin,Alemanya,76,8.5,Continental
27,Munchen,Alemanya,82,8.0,Continental
28,Hamburg,Alemanya,78,8.1,Oceànic
29,Frankfurt,Alemanya,80,8.3,Continental
30,Stuttgart,Alemanya,79,7.9,Continental
31,Leipzig,Alemanya,70,7.2,Continental
32,Oslo,Noruega,90,9.2,Fred
33,Bergen,Noruega,85,8.8,Oceànic
34,Paris,Estats Units,88,6.0,Continental
35,Valencia,Veneçuela,55,5.5,Tropical

Corregimos manualmente el error de codigo que surge de forma aislada para A Coruña.

In [ ]:
ciutats['Ciutat'] = ciutats['Ciutat'].replace('A Coru\\u00f1a', 'A Coruña')

In [ ]:
ciutats[ciutats['Ciutat'] == 'A Coruña']

      Ciutat     País  Cost_vida_index  Transport_public_score Clima_tipus
10  A Coruña  Espanya               69                     7.1     Oceànic

Comprobamos consistencia de las ciudades entre los dos ficheros antes de unirlos.

In [ ]:
ciudades_en_Ciutat = set(ciutats['Ciutat'].unique()) - set(df['Ciutat'].unique())
ciudades_en_df = set(df['Ciutat'].unique()) - set(ciutats['Ciutat'].unique())
display(ciudades_en_Ciutat)
display(ciudades_en_df)

{'Munchen', 'Valencia'}

{'Bologna',
 'Düsseldorf',
 'Köln',
 'Màlaga',
 'München',
 'Nantes',
 'Nice',
 'Stavanger',
 'Toulouse',
 'Tromsø',
 'Trondheim'}

Unificamos "München" en "Munchen". Hacemos el cambio en nuestro dataset principal.

In [ ]:
df['Ciutat'] = df['Ciutat'].replace('München', 'Munchen')

Tras revisar los datasets, procederemos a integrar el dataset principal con "ciutats" utilizando la columna "Ciutat" como clave combinado con la columna "País d'origen" para evitar duplicas con ciudades como Paris que existe en paises diferentes.

In [ ]:
# Integramos el DataFrame principal con el DataFrame de ciudades
df2 = pd.merge(
    df,
    ciutats,
    left_on=['Ciutat', 'País d\'origen'], # nombre columnas en df de la izquierda
    right_on=['Ciutat', 'País'], # nombre columnas en df de la derecha
    how='left'
)

In [ ]:
# Filtramos df2 con alguna de las nuevas columnas para revisar las filas que no se han podido completar
cost_vacio = df2[df2['Cost_vida_index'].isna()]
print(cost_vacio['Ciutat'].value_counts())
print(cost_vacio['Ciutat'].count())

Ciutat
Màlaga        54
Toulouse      15
Nantes        12
Bologna       11
Nice          11
Stavanger      9
Trondheim      6
Düsseldorf     5
Tromsø         4
Köln           4
Name: count, dtype: int64
131

131 filas no se han podido completar, corresponden a los empleados que viven en las 10 ciudades que no existian en ciutats_context.csv.

Comprobamos en el nuevo dataset que las celdas de las nuevas columnas (País,	Cost_vida_index,	Transport_public_score,	Clima_tipus) contengan NaN para aquellas ciudades, por ejemplo con Stavanger:

In [ ]:
df2[(df2['Ciutat'] == "Stavanger")]

,ID,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,...,Nombre_fills,Te_cotxe,Km_anuals,Consum_mitja_L_100km,Temperatura_mitjana_ciutat,Salari mensual_euros,País,Cost_vida_index,Transport_public_score,Clima_tipus
8,540,Nora,Andersen Pedersen,37289414J,Noruega,Stavanger,8.0,3.0,1963.0,Dona,...,0.0,False,NaN,NaN,7.60,1338.0,NaN,NaN,NaN,NaN
110,958,Maja,Eriksen,69314812J,Noruega,Stavanger,20.0,2.0,1975.0,Dona,...,4.0,<NA>,NaN,NaN,5.80,1244.0,NaN,NaN,NaN,NaN
314,589,Thea,Kristiansen,90402724B,Noruega,Stavanger,31.0,10.0,2004.0,Dona,...,NaN,True,NaN,NaN,7.85,3061.0,NaN,NaN,NaN,NaN
366,452,Thea,Lie,23933416W,Noruega,Stavanger,26.0,2.0,1964.0,Dona,...,0.0,<NA>,NaN,NaN,7.00,847.0,NaN,NaN,NaN,NaN
589,674,Emil,Moen,14887763Y,Noruega,Stavanger,26.0,3.0,1989.0,Home,...,NaN,False,NaN,NaN,8.70,1501.0,NaN,NaN,NaN,NaN
637,115,Sigrid,Hansen,23656928V,Noruega,Stavanger,19.0,2.0,2003.0,Home,...,NaN,<NA>,NaN,NaN,8.10,1524.0,NaN,NaN,NaN,NaN
641,316,Ole,Berg,65426729X,Noruega,Stavanger,16.0,8.0,1963.0,Home,...,NaN,<NA>,NaN,NaN,9.90,2019.0,NaN,NaN,NaN,NaN
686,652,Kristian,Lie,15190410S,Noruega,Stavanger,NaN,NaN,NaN,Home,...,0.0,<NA>,NaN,NaN,8.50,939.0,NaN,NaN,NaN,NaN
827,599,Sofie,Eriksen Haugen,54363421F,Noruega,Stavanger,10.0,11.0,2002.0,Home,...,NaN,False,NaN,NaN,6.50,3610.0,NaN,NaN,NaN,NaN

> Integrar el dataset principal amb la política salarial definida en format JSON

In [ ]:
with open('/content/drive/MyDrive/Colab Notebooks/politica_salarial.json', "r", encoding="utf-8") as f:
  ps = json.load(f)

In [ ]:
ps

{'base_increment_by_group': {'Grup A': 5.0,
  'Grup B': 3.5,
  'Grup C': 2.0,
  'Grup D': 8.0},
 'children_adjustment': {'has_children': 1.5, 'no_children': 0.0},
 'age_adjustment': {'18-29': 0.0, '30-44': 1.0, '45-59': 2.0, '60+': 1.5},
 'cost_of_living_adjustment': {'low': 0.0, 'medium': 1.0, 'high': 2.0},
 'transport_adjustment': {'low': 0.5, 'medium': 0.0, 'high': -0.5},
 'rules': {'max_total_increment_percent': 15, 'min_salary_threshold': 800}}

**franjas de edad:** Crearemos una nueva columna para categorizar la edad de los empleados según las franjas especificadas en politica_salarial.

Se debe crear primero la fecha de nacimiento a partir de las 3 columnas dia, mes y any de naixement.

Despues calcumos la edad que es la resta entre el dia de hoy y la fecha de nacimiento.

Por ultimo se crea la columna Franja_edat y se asigna una de las 4 franjas.

In [ ]:
# Creamos una fecha de nacimiento temporalmente
fecha_nacimiento = pd.to_datetime(
    {
        "year": df2["Any de Naixement"],
        "month": df2["Mes de Naixement"],
        "day": df2["Dia de Naixement"]
    },
    errors="coerce"
)

# Calculamos la edad: contempla años bisiestiles y que devuelva un numero entero inferior (si 20,6, guardamos 20 años)
hoy = pd.Timestamp.today()

df2["Edat"] = np.floor(
    (hoy - fecha_nacimiento).dt.days / 365.25 # "365.25"contempla años bisiestiles y np.floor devuelve la parte entera del decimal (si 20,6, guardamos 20 años)
).astype("Int64")

# Definimos las franjas de edad
condiciones = [
    df2["Edat"].between(18, 29).fillna(False),
    df2["Edat"].between(30, 44).fillna(False),
    df2["Edat"].between(45, 59).fillna(False),
    (df2["Edat"] >= 60).fillna(False)
]

franjas = ["18-29", "30-44", "45-59", "60+"]

df2["Franja edat"] = np.select(
    condiciones,
    franjas,
    default=pd.NA
)

In [ ]:
# Comprobamos que la edad se ha calculado bien y que la franja corecta se ha asignado con las 10 primeras filas
fecha = pd.to_datetime(
    {
        "year": df2["Any de Naixement"],
        "month": df2["Mes de Naixement"],
        "day": df2["Dia de Naixement"]
    },
    errors="coerce"
)

edad = ((pd.Timestamp.today() - fecha).dt.days / 365.25).round()

print(
    pd.DataFrame({
        "año": df2["Any de Naixement"],
        "edad": edad,
        "franja": df2["Franja edat"]
    }).head(10)
)

      año  edad franja
0  1958.0  69.0    60+
1  1960.0  66.0    60+
2  1961.0  65.0    60+
3  1985.0  41.0  30-44
4  1965.0  61.0    60+
5  1978.0  48.0  45-59
6  1971.0  55.0  45-59
7  1962.0  64.0    60+
8  1963.0  64.0    60+
9  1940.0   NaN   <NA>

**Ajuste por costo de vida:**

No existe un rango oficial rígido pero varias plataformas coinciden en establecer el intervalo de indice tal como:

High > 80  /  Medium 40 - 80  /  Low < 40

Cuadra con los valores que tenemos en nuestro dataset

In [ ]:
maximo = df2.loc[df2["Cost_vida_index"].idxmax()]
minimo = df2.loc[df2["Cost_vida_index"].idxmin()]

print(maximo["Ciutat"], "-", maximo["Cost_vida_index"])
print(minimo["Ciutat"], "-", minimo["Cost_vida_index"])

Oslo - 90.0
Murcia - 60.0

Creamos la nueva columna "ajust_cost_vida" con los 3 intervalos "Low", "Medium", "High" segun los valores de la columna "Cost_vida_index".

In [ ]:
condiciones = [
    df2["Cost_vida_index"] < 40,
    df2["Cost_vida_index"].between(40, 80),
    df2["Cost_vida_index"] > 80
]

categorias = ["Low", "Medium", "High"]

df2["Ajust cost vida"] = np.select(condiciones,categorias,default=pd.NA)
print(df2["Ajust cost vida"].value_counts())

Ajust cost vida
Medium    820
High       37
Name: count, dtype: int64

> Calcular un increment salarial total combinant:

Grup professional
 *'base_increment_by_group'*:
  *   'Grup A': 5.0
  *   'Grup B': 3.5
  *   'Grup C': 2.0
  *   'Grup D': 8.0

Situació familiar
  *children_adjustment'*:
  *   'has_children': 1.5
  *   'no_children': 0.0

Franja d'edat
  *'age_adjustment'*:
  *   '18-29': 0.0
  *   '30-44': 1.0
  *   '45-59': 2.0
  *   '60+': 1.5

Cost de vida de la ciutat
  *'cost_of_living_adjustment'*:
  *   'low': 0.0
  *   'medium': 1.0
  *   'high': 2.0

*'transport_adjustment'*: 'low': 0.5, 'medium': 0.0, 'high': -0.5

*'rules'*: 'max_total_increment_percent': 15, 'min_salary_threshold': 800

Calcularemos cada incremento individualmente. Creamos primero diccionarios para cada elemento

In [ ]:
base_increment_by_group = {
    'Grup A': 5.0,
    'Grup B': 3.5,
    'Grup C': 2.0,
    'Grup D': 8.0
}

age_adjustment = {
    '18-29': 0.0,
    '30-44': 1.0,
    '45-59': 2.0,
    '60+': 1.5
}

cost_of_living_adjustment = {
    'Low': 0.0,
    'Medium': 1.0,
    'High': 2.0
}

Crearemos una columna por tipo de incremento

-'inc_grup' para Grup professional

-'inc_fills' para Situació familiar

-'inc_edat' para Franja d'edat

-'inc_cost_vida' para Cost de vida de la ciutat

In [ ]:
df2['inc grup'] = df2['Grup Professional'].map(base_increment_by_group)


df2['inc fills'] = np.where(
    df2['Nombre_fills'].isna(), # condición: si falta el numero de hijos
    np.nan, # entonces el incremento es NaN
    np.where(df2['Nombre_fills'] > 0, 1.5, 0.0) # si existe, se calcula el incremento
)

df2['inc edat'] = df2['Franja edat'].map(age_adjustment)

df2['inc cost vida'] = df2['Ajust cost vida'].map(cost_of_living_adjustment)

Calculamos el nuevo salario

In [ ]:
df2['Increment total'] = (df2['inc grup'] + df2['inc fills'] + df2['inc edat'] + df2['inc cost vida'])

df2['Salari ajustat'] = (df2['Salari mensual_euros'] * (1 + df2['Increment total'] / 100))

> Identificar quins registres no poden rebre algun dels ajustos i explicar-ne el motiu.

Crearemos una nueva columna que identifique las filas donde algún ajuste salarial que no se ha podido calcular.

In [ ]:
df2['Ajust incomplet'] = (
    df2[['inc grup',
         'inc fills',
         'inc edat',
         'inc cost vida']]
    .isna()
    .any(axis=1)
)

Y creamos otra columna que nos indica qué dato falto para poder aplicar todos los ajustes

In [ ]:
def motiu_incomplet(row):

    motivos = []

    if pd.isna(row['inc grup']):
        motivos.append('Grup profesional')

    if pd.isna(row['inc fills']):
        motivos.append('Nombre fills')

    if pd.isna(row['inc edat']):
        motivos.append('Franja edat')

    if pd.isna(row['inc cost vida']):
        motivos.append('Cost vida')

    return '; '.join(motivos)

df2['Motius incomplet'] = df2.apply(motiu_incomplet, axis=1)

In [ ]:
df2_muestra = pd.concat([df2.head(5), df2.sample(10), df2.tail(5)])
display(df2_muestra)

,ID,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,...,Franja edat,Ajust cost vida,inc grup,inc fills,inc edat,inc cost vida,Increment total,Salari ajustat,Ajust incomplet,Motius incomplet
0,0,Joana,Gil Navarro,66722344X,Espanya,Valladolid,23.0,3.0,1958.0,Dona,...,60+,Medium,3.5,1.5,1.5,1.0,7.5,1579.175,False,
1,1,Marc,Muñoz,48840994W,Espanya,Alacant,8.0,11.0,1960.0,Home,...,60+,Medium,2.0,0.0,1.5,1.0,4.5,2840.310,False,
2,2,Noa,Serra,14308421X,Espanya,Alacant,27.0,4.0,1961.0,Dona,...,60+,Medium,5.0,1.5,1.5,1.0,9.0,1480.220,False,
3,3,Pol,Gil,58586340F,Espanya,Sevilla,13.0,10.0,1985.0,Home,...,30-44,Medium,3.5,1.5,1.0,1.0,7.0,1581.460,False,
4,4,David,Vila,82070937P,Espanya,Bilbao,29.0,11.0,1965.0,Dona,...,60+,Medium,3.5,NaN,1.5,1.0,NaN,NaN,True,Nombre fills
374,8,Lars,Eriksen,35529407V,Noruega,Oslo,7.0,4.0,1964.0,Home,...,60+,High,5.0,NaN,1.5,2.0,NaN,NaN,True,Nombre fills
758,773,Pol,Soler Sánchez,34254080R,Espanya,Tarragona,30.0,3.0,1964.0,Home,...,60+,Medium,5.0,1.5,1.5,1.0,9.0,833.850,False,
700,36,Ida,Larsen,46698468J,Noruega,Oslo,17.0,5.0,2003.0,Home,...,18-29,High,5.0,1.5,0.0,2.0,8.5,1061.130,False,
40,42,Laia,Puig,57287718F,Espanya,Girona,20.0,4.0,1976.0,Dona,...,45-59,Medium,5.0,0.0,2.0,1.0,8.0,1553.040,False,
911,927,Anna,Pérez Serra,81260169S,Espanya,Barcelona,11.0,2.0,1983.0,Home,...,30-44,Medium,3.5,1.5,1.0,1.0,7.0,2061.890,False,
44,46,Joana,Gil Ferrer,75679047L,Espanya,Girona,4.0,11.0,1984.0,Dona,...,30-44,Medium,2.0,1.5,1.0,1.0,5.5,2247.150,False,
771,786,Pol,Serra,86297749A,Espanya,Sevilla,19.0,5.0,1996.0,Home,...,30-44,Medium,2.0,1.5,1.0,1.0,5.5,2240.820,False,
626,636,Jade,Lefebvre,71195665P,França,Marseille,9.0,2.0,1978.0,Home,...,45-59,Medium,2.0,1.5,2.0,1.0,6.5,3000.105,False,
6,6,David,Gómez Vila,36998038E,Espanya,Palma,25.0,9.0,1971.0,Dona,...,45-59,Medium,3.5,NaN,2.0,1.0,NaN,NaN,True,Nombre fills
244,251,Camille,Fournier,52746321P,França,Lyon,18.0,6.0,1992.0,Home,...,30-44,Medium,5.0,1.5,1.0,1.0,8.5,1368.185,False,
983,999,Adrià,Vila Díaz,57511543T,Espanya,Palma,31.0,12.0,1991.0,Home,...,30-44,Medium,2.0,1.5,1.0,1.0,5.5,2120.550,False,
984,651,Kasper,Pettersen,62042563B,Noruega,Oslo,11.0,5.0,1996.0,Dona,...,30-44,High,3.5,0.0,1.0,2.0,6.5,2438.850,False,
985,1002,Alba,Muñoz,97954019T,Espanya,Bilbao,25.0,10.0,1983.0,Dona,...,30-44,Medium,3.5,0.0,1.0,1.0,5.5,1486.495,False,
986,1003,Claudia,Gil Ferrer,55297384F,Espanya,València,1.0,11.0,1981.0,Home,...,30-44,Medium,3.5,0.0,1.0,1.0,5.5,1887.395,False,
987,1004,Oriol,Ferrer,52590001R,Espanya,Zaragoza,15.0,7.0,1973.0,Dona,...,45-59,Medium,5.0,0.0,2.0,1.0,8.0,848.880,False,

Comprobemos como han quedado las filas tras realizar estas operaciones. Que ajustes se han completado y en que proporcion?

In [ ]:
df2[['Increment total','inc grup', 'inc fills','inc edat', 'inc cost vida']].count()

Increment total    556
inc grup           988
inc fills          693
inc edat           911
inc cost vida      857
dtype: int64

**'transport_adjustment'**
La política salarial proporciona los porcentajes asociados a las categorías de transporte público (low, medium y high), pero no define como asignar cada ciudad a una categoría concreta. Dado que no existe ningun dato oficial (como era el caso para el indice de coste de vida, aunque "semi-official") ni tampoco una regla objetiva que determine los valores de las categorías, preferimos no incluir este ajuste en el cálculo salarial para evitar introducir supuestos arbitrarios que podrían alterar los resultados finales.

No obstante calculamos de forma exploratoria un posible ajuste comparando dos metodos, terciles vs rupturas naturales.

In [ ]:
# Ajuste aplicando Terciles (Divide el total en tres partes iguales)
transport_adjustment = {
    'low': 0.5,
    'medium': 0.0,
    'high': -0.5
}

# Clasificación en 3 grupos
ciutats['Cat_transport_terciles'] = pd.qcut(
    ciutats['Transport_public_score'],
    q=3,
    labels=['low', 'medium', 'high']
)
ciutats['inc_transport_terciles'] = (ciutats['Cat_transport_terciles'].map(transport_adjustment))

In [ ]:
!pip install jenkspy

Requirement already satisfied: jenkspy in /usr/local/lib/python3.13/dist-packages (0.4.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.13/dist-packages (from jenkspy) (2.1.3)

In [ ]:
import jenkspy
# Ajuste aplicando las rupturas naturales de Jenks

transport_adjustment = {
    'low': 0.5,
    'medium': 0.0,
    'high': -0.5
}
# Configuramos que se crean 3 grupos
breaks = jenkspy.jenks_breaks(
    ciutats['Transport_public_score'],
    n_classes=3
)
ciutats['Cat_transport_jenks'] = pd.cut(
    ciutats['Transport_public_score'],
    bins=breaks,
    labels=['low', 'medium', 'high'],
    include_lowest=True
)
ciutats['inc_transport_jenks'] = (ciutats['Cat_transport_jenks'].map(transport_adjustment))

In [ ]:
ciutats[['Cat_transport_terciles', 'Cat_transport_jenks', 'Ciutat', 'País', 'Transport_public_score']].sort_values(['Cat_transport_terciles', 'Cat_transport_jenks', 'Transport_public_score'])

,Cat_transport_terciles,Cat_transport_jenks,Ciutat,País,Transport_public_score
35,low,low,Valencia,Veneçuela,5.5
34,low,low,Paris,Estats Units,6.0
6,low,low,Murcia,Espanya,6.5
24,low,low,Napoli,Itàlia,6.5
11,low,medium,Valladolid,Espanya,6.7
8,low,medium,Girona,Espanya,6.8
13,low,medium,Las Palmas de Gran Canaria,Espanya,6.8
9,low,medium,Tarragona,Espanya,6.9
22,low,medium,Genova,Itàlia,6.9
3,low,medium,Sevilla,Espanya,7.0
5,low,medium,Zaragoza,Espanya,7.0
12,low,medium,Alacant,Espanya,7.0
23,low,medium,Venezia,Itàlia,7.0
10,medium,medium,A Coruña,Espanya,7.1
25,medium,medium,Firenze,Itàlia,7.1
7,medium,medium,Palma,Espanya,7.2
17,medium,medium,Bordeaux,França,7.2
21,medium,medium,Torino,Itàlia,7.2
31,medium,medium,Leipzig,Alemanya,7.2
18,medium,medium,Lille,França,7.3
15,medium,medium,Marseille,França,7.4
2,medium,medium,València,Espanya,7.5
19,medium,medium,Milano,Itàlia,7.5
16,medium,medium,Lyon,França,7.6
20,medium,medium,Roma,Itàlia,7.6
4,high,high,Bilbao,Espanya,7.8
30,high,high,Stuttgart,Alemanya,7.9
1,high,high,Madrid,Espanya,8.0
27,high,high,Munchen,Alemanya,8.0
28,high,high,Hamburg,Alemanya,8.1
29,high,high,Frankfurt,Alemanya,8.3
0,high,high,Barcelona,Espanya,8.5
26,high,high,Berlin,Alemanya,8.5
33,high,high,Bergen,Noruega,8.8
14,high,high,Paris,França,9.0
32,high,high,Oslo,Noruega,9.2

Comparativa entre terciles y Jenks:

El método de terciles divide las ciudades en tres grupos aproximadamente iguales (no son 3 grupos exactamente iguales debido a que hay empates entre ciudades) según su posición dentro de la distribución. En cambio, el método de Jenks busca identificar agrupaciones naturales, estableciendo los puntos de corte donde existen mayores diferencias entre los valores.

Ambos métodos coinciden en la clasificación de las puntuaciones más bajas y más altas, pero presentan diferencias en los valores comprendidos entre 6,7 y 7,0.

Los terciles clasifican estas ciudades dentro de la categoría low, mientras que Jenks las incluye en medium. Por tanto, Jenks genera un grupo bajo más reducido y amplía el grupo medio.

A nivel cuantitativo, al comparar las categorías de ambos métodos, 333 empleados dejarían de estar en la categoría low al aplicar el método de Jenks y pasarían a la categoría medium. Esto implica que, para estos 333 empleados, dejaría de aplicarse el ajuste al alza de +0,5 asociado a la categoría low, ya que la categoría medium tiene un factor de ajuste de 0.

In [ ]:
# Ciudades LOW con terciles
ciudades_low_terciles = ciutats.loc[
    ciutats['Cat_transport_terciles'] == 'low','Ciutat']

# Ciudades LOW con Jenks
ciudades_low_jenks = ciutats.loc[ciutats['Cat_transport_jenks'] == 'low','Ciutat']


# Empleados que viven en esas ciudades
empleados_terciles = df2[df2['Ciutat'].isin(ciudades_low_terciles)]
empleados_jenks = df2[df2['Ciutat'].isin(ciudades_low_jenks)]

print("Empleados afectados con terciles:", len(empleados_terciles))
print("Empleados afectados con Jenks:", len(empleados_jenks))

Empleados afectados con terciles: 410
Empleados afectados con Jenks: 78

**Reglas**

'rules': 'max_total_increment_percent': 15, 'min_salary_threshold': 800

- El incremento total no puede superar el 15% del salario
- El salario no podrá ser inferior a 800€ (ajustes incluidos).

In [ ]:
rules = {
    'max_total_increment_percent': 15,
    'min_salary_threshold': 800
}
# Simulamos el incremento respetando el máximo del 15%
incremento_simulado = df2['Increment total'].clip(
    upper=rules['max_total_increment_percent']
)

# Simulamos el salario
salario_simulado = (
    df2['Salari mensual_euros'] *
    (1 + incremento_simulado / 100)
).round(2)

# Comprobamos qué filas se veran afectadas
df2[salario_simulado < rules['min_salary_threshold']]

,ID,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,...,Franja edat,Ajust cost vida,inc grup,inc fills,inc edat,inc cost vida,Increment total,Salari ajustat,Ajust incomplet,Motius incomplet
259,266,Ilaria,Colombo,11419753K,Itàlia,Napoli,18.0,6.0,1969.0,Dona,...,45-59,Medium,5.0,1.5,2.0,1.0,9.5,792.780,False,
342,350,Alejandro,Gómez López,17907267L,Espanya,Bilbao,6.0,11.0,1984.0,Dona,...,30-44,Medium,5.0,1.5,1.0,1.0,8.5,779.030,False,
573,583,Alessandro,Barbieri,59046143J,Itàlia,Milano,19.0,5.0,2001.0,Dona,...,18-29,Medium,5.0,0.0,0.0,1.0,6.0,743.060,False,
843,858,Joana,Casals Puig,94227868E,Espanya,A Coruña,26.0,9.0,1983.0,Home,...,30-44,Medium,5.0,1.5,1.0,1.0,8.5,787.710,False,
931,947,Marc,García Gómez,29915816T,Espanya,Girona,22.0,8.0,2004.0,Altres opcions,...,18-29,Medium,5.0,1.5,0.0,1.0,7.5,723.475,False,

In [ ]:
rules = {
    'max_total_increment_percent': 15,
    'min_salary_threshold': 800
}

# Establecemos el limite total de los ajustes en un 15%
df2['Increment total'] = df2['Increment total'].clip(upper=rules['max_total_increment_percent'])

# Calculamos el salario con el incremento definitivo
df2['Salari ajustat'] = (df2['Salari mensual_euros'] *(1 + df2['Increment total'] / 100)).round(2)

# Garantizamos que el salario final no sea inferior a 800€
df2['Salari ajustat'] = df2['Salari ajustat'].clip(lower=rules['min_salary_threshold'])

In [ ]:
# Comprobamos que los 5 empleados ya tienen un salario minimo de 800€
df2.loc[df2['Salari ajustat'] == rules['min_salary_threshold'],['Salari mensual_euros', 'Salari ajustat']]

     Salari mensual_euros  Salari ajustat
259                 724.0           800.0
342                 718.0           800.0
573                 701.0           800.0
843                 726.0           800.0
931                 673.0           800.0

In [ ]:
df2[df2['Salari ajustat'] < rules['min_salary_threshold']]

Empty DataFrame
Columns: [ID, Nom, Cognoms, DNI, País d'origen, Ciutat, Dia de Naixement, Mes de Naixement, Any de Naixement, Gènere, Salari mensual, Grup Professional, Càrrec, Nombre_fills, Te_cotxe, Km_anuals, Consum_mitja_L_100km, Temperatura_mitjana_ciutat, Salari mensual_euros, País, Cost_vida_index, Transport_public_score, Clima_tipus, Edat, Franja edat, Ajust cost vida, inc grup, inc fills, inc edat, inc cost vida, Increment total, Salari ajustat, Ajust incomplet, Motius incomplet]
Index: []

[0 rows x 34 columns]

Observaciones sobre los ajustes aplicados segun la politica salarial:


**incremento grup** : 992/992 completados
*   Se pudo completar todas las filas ya que todas tienen el grupo profesional
informado.

**incremento fills** : 697/992 completados
*   La diferencia de 295 son las filas con valores nulos ya que mo hemos implementado incremento sobre ellos.

**incremento edat** : 915/992 completados
*   Las filas faltantes son las para las cuales no hemos podido calcular la edad al no disponer de los 3 componentes necesarios que eran dia , mes y año de nacimiento. Hay 77 filas donde falta al menos uno de estos 3 valores, estos valores nulos o ya venian "informados" asi en la encuesta, o nosotros los pasamos a nulos por ser valores incoherentes.

**incremento cost vida** : 861/992 completados
*   Son las 131 filas que corresponden a los empleados que viven en las 10 ciudades que no existian en ciutats_context.csv., ex: Màlaga, Toulouse.

**incremento total** : 560/992 completados
*   Esto nos permite observar a mayor escala que para 56.45 % de los empleados, algun incremento no se pudo aplicar, y eso proviene de como hemos tratado los datos brutos desde el inicio de este sprint.

**Regla max 15%** : no ha repercutido en ningun salario

**Regla min 800€** : 5 empleados se han visto el sueldo subir a 800€

# Exercici 2: Reestructuració del dataset

> Reestructurar el dataset utilitzant melt() per convertir-lo a format llarg, definint prèviament:

- les columnes que actuen com a identificadores (per exemple: persona, ciutat, grup professional, gènere, etc.).

- les columnes que passen a representar valors mesurats (per exemple: salaris, mobilitat, variables contextuals).

Reestructuración del dataset a formato largo:

- Separamos las variables identificadoras/categóricas de las medidas.

- Las medidas seleccionadas corresponden a salario, movilidad, contextoy número de hijos.

Con melt(), cada persona tendrá una fila por cada medida, identificada mediante las columnas 'Variable' y 'Valor'.

In [ ]:
# definimos las columnas identificadora
identificadoras = [
    'ID',
    'Nom',
    'Cognoms',
    'Ciutat',
    'País',
    'Gènere',
    'Franja edat',
    'Nombre_fills',
    'Grup Professional',
    'Càrrec',
]

In [ ]:
# definimos las columnas de las medidas

salario = [
    'Salari ajustat',
]

movilidad = [
    'Te_cotxe',
    'Km_anuals',
    'Consum_mitja_L_100km'
]

contexto = [
    'Temperatura_mitjana_ciutat',
    'Cost_vida_index',
    'Transport_public_score'
]

In [ ]:
# Creamos un dataframe para cada medida
df_salario = df2.melt(
    id_vars=identificadoras,
    value_vars=salario,
    var_name='Variables salario',
    value_name='Valor'
)

df_movilidad = df2.melt(
    id_vars=identificadoras,
    value_vars=movilidad,
    var_name='Variables movilidad',
    value_name='Valor'
).sort_values(by='ID')

df_contexto = df2.melt(
    id_vars=identificadoras,
    value_vars=contexto,
    var_name='Variables contexto',
    value_name='Valor'
).sort_values(by='ID')

In [ ]:
# Muestra
df_movilidad.head(12)

,ID,Nom,Cognoms,Ciutat,País,Gènere,Franja edat,Nombre_fills,Grup Professional,Càrrec,Variables movilidad,Valor
0,0,Joana,Gil Navarro,Valladolid,Espanya,Dona,60+,3.0,Grup B,Cap de projecte,Te_cotxe,True
1976,0,Joana,Gil Navarro,Valladolid,Espanya,Dona,60+,3.0,Grup B,Cap de projecte,Consum_mitja_L_100km,25.0
988,0,Joana,Gil Navarro,Valladolid,Espanya,Dona,60+,3.0,Grup B,Cap de projecte,Km_anuals,32108.0
1977,1,Marc,Muñoz,Alacant,Espanya,Home,60+,0.0,Grup C,Senior analyst,Consum_mitja_L_100km,10.4
989,1,Marc,Muñoz,Alacant,Espanya,Home,60+,0.0,Grup C,Senior analyst,Km_anuals,19496.0
1,1,Marc,Muñoz,Alacant,Espanya,Home,60+,0.0,Grup C,Senior analyst,Te_cotxe,True
1978,2,Noa,Serra,Alacant,Espanya,Dona,60+,4.0,Grup A,Tècnic IT,Consum_mitja_L_100km,NaN
2,2,Noa,Serra,Alacant,Espanya,Dona,60+,4.0,Grup A,Tècnic IT,Te_cotxe,<NA>
990,2,Noa,Serra,Alacant,Espanya,Dona,60+,4.0,Grup A,Tècnic IT,Km_anuals,NaN
991,3,Pol,Gil,Sevilla,Espanya,Home,30-44,2.0,Grup B,Data analyst,Km_anuals,NaN
1979,3,Pol,Gil,Sevilla,Espanya,Home,30-44,2.0,Grup B,Data analyst,Consum_mitja_L_100km,NaN
3,3,Pol,Gil,Sevilla,Espanya,Home,30-44,2.0,Grup B,Data analyst,Te_cotxe,False

> Analitzar per què el format llarg és més adequat per:

- realitzar comparacions entre diferents tipus de variables.
- calcular estadístics agregats.

El formato largo facilita la comparación entre diferentes tipos de variables porque estas quedan agrupadas en una única columna (Variable), mientras que sus valores se concentran en la columna Valor. Esto permite seleccionar, filtrar y comparar fácilmente variables como el salario ajustado, la movilidad o las variables contextuales.

También facilita el cálculo de estadísticos agregados, ya que podemos agrupar los datos por Variable o por otras características, como el género, el grupo profesional, la ciudad o la franja de edad, y calcular estadísticos como la media, la mediana, el mínimo o el máximo.

In [ ]:
# Probamos de replicar el "Exercici 4: Primeres anàlisis descriptives (Crear una taula resum amb el salari mig per gènere i país d'origen)" con el formato largo
df_salario.groupby(["País", "Gènere"])["Valor"].mean().round(2)

País      Gènere
Alemanya  Altres opcions    1723.87
          Dona              1613.99
          Home              2160.05
Espanya   Altres opcions    1769.89
          Dona              1549.21
          Home              1861.97
França    Altres opcions    2199.79
          Dona              1652.34
          Home              2024.05
Itàlia    Altres opcions    2558.95
          Dona              1655.46
          Home              1779.25
Noruega   Altres opcions    1335.96
          Dona              1858.44
          Home              1481.58
Name: Valor, dtype: float64

In [ ]:
# Con formato largo, podemos obtener los estadísticos agregados de todas las variables a la vez
df_movilidad.groupby('Variables movilidad')['Valor'].agg([pd.Series.mean, pd.Series.median, pd.Series.std])

                              mean   median           std
Variables movilidad
Consum_mitja_L_100km     11.068605      9.9      8.815700
Km_anuals             55928.442308  55379.0  62358.621922
Te_cotxe                  0.503876      1.0      0.500373

# Exercici 3: Creació de variables derivades (Feature Engineering)

> Crear almenys 3 variables derivades.

>  Justificar:
La seva utilitat analítica.
Les decisions preses.

>  Detectar casos límit o incoherents generats per les noves variables.

1. Index_dependencia_familiar

   Salari ajustat / (Nombre_fills + 1)

2. Ratio_salario_coste_vida

   Salari ajustat / Cost_vida_index

3. Pes_responsabilitat_familiar

   Nombre_fills * Edat

Para cada variable procederemos de la siguiente manera:
1. calculo de la variable
2. sacar una muestra incluyendo los componentes de la variable
3. hacer un describe para mayor contexto
4. revisar cantidad de NaN
5. revisar de donde provienen los NaN
6. comprobar la utilidad de la variable con un ejemplo
7. conclusiones

**Index_dependencia_familiar**

In [ ]:
# 1. Calculamos el indice
df2["Index_dependencia_familiar"] = (df2["Salari ajustat"] / (df2["Nombre_fills"] + 1)).round(2)

In [ ]:
# 2. Muestra
df2[ ["Salari ajustat",
        "Nombre_fills",
        "Index_dependencia_familiar"]].head(10)

In [ ]:
# 3. descripcion global
df2["Index_dependencia_familiar"].describe()

In [ ]:
# 4. cuantos NaN se han generado?
nulos = df2["Index_dependencia_familiar"].isna().sum()
nulos

In [ ]:
# 5. de donde provienen los NaN ?
motivo_nulos = df2.loc[ df2["Index_dependencia_familiar"].isna(),["Salari ajustat", "Nombre_fills"]].isna().sum()
motivo_nulos

In [ ]:
# comparamos el salario medio con el índice medio entre los empleados sin hijos y los que tienen 3 hijos o mas
sin_hijos = df2[df2['Nombre_fills'] == 0][['Salari ajustat', 'Index_dependencia_familiar']].median()
con_hijos = df2[df2['Nombre_fills'] >= 3][['Salari ajustat', 'Index_dependencia_familiar']].median()

comparativa = pd.DataFrame([sin_hijos, con_hijos], index=['Empleado sin hijos (Mediana)', 'Empleado con 3+ hijos (Mediana)'])
print(comparativa.round(2))

7. Conclusiones

Utilidad analítica: permite relacionar el salario con el número de hijos y aproximar la disponibilidad económica según la carga familiar.

Con nuestro ejemplo vemos que a salarios parecidos, el index cae drásticamente.


Decisiones tomadas: se utiliza (Nombre_fills + 1) para incluir a la propia persona en el cálculo y evitar divisiones entre cero cuando no tiene hijos.

Casos límite o incoherentes: observamos que el valor del indice es igual al salario cuando un empleado no tiene hijos.

Se han detectado 432 valores nulos, generados cuando falta uno o ambos datos necesarios parea el calculo. Se mantienen como NaN para evitar generar valores artificiales. Hay bastantes NaN pero cuadran con lo que observamos [previamente](https://colab.research.google.com/drive/1DjVQz2QG-yuYXVcAA9slFzgEnra2D_fr#scrollTo=NY-V1_rrFvqD&line=2&uniqifier=1).

**Ratio_salario_coste_vida**

In [ ]:
# 1. Calculamos el ratio
df2["Ratio_salari_cost_vida"] = ( df2["Salari ajustat"] / df2["Cost_vida_index"]).round(2)

In [ ]:
# 2. Muestra
df2[ ["Salari ajustat",
        "Cost_vida_index",
        "Ratio_salari_cost_vida"]].head(10)

In [ ]:
# 3. descripcion global
df2["Ratio_salari_cost_vida"].describe()

In [ ]:
# 4. cuantos NaN se han generado?
nulos = df2["Ratio_salari_cost_vida"].isna().sum()
nulos

In [ ]:
# 5. de donde provienen los NaN ?
motivo_nulos = df2.loc[ df2["Ratio_salari_cost_vida"].isna(),["Salari ajustat", "Cost_vida_index"]].isna().sum()
motivo_nulos

In [ ]:
# 6. observamos como cambia el ratio comparando 2 empleados de la misma ciudad con salarios muy diferentes
ciudad_mas_empleados = df2['Ciutat'].value_counts().idxmax()
df2.loc[df2["Ciutat"] == ciudad_mas_empleados, ["Salari ajustat", "Cost_vida_index", "Ratio_salari_cost_vida"]].agg(["min", "max"])

7. Conclusiones

Utilidad analítica: permite relacionar el salario con el nivel de coste de vida de la ciudad, aportando más contexto que analizar únicamente el salario.

Nos permite comprobar que empleados viviendo en la misma ciudad no tienen la misma calidad de vida.

Casos límite o incoherentes:  si Salari ajustat o Cost_vida_index contiene un valor nulo, el indicador también será NaN. Por otro lado se debe contemplar que Cost_vida_index no sea igual a 0, porque provocarían una división problemática.

**Pes_responsabilitat_familiar**

In [ ]:
# 1. Calculamos la variable
df2["Pes_responsabilitat_familiar"] = (df2["Nombre_fills"] * df2["Edat"])

In [ ]:
# 2. Muestra
df2[ ["Nombre_fills",
        "Edat",
        "Pes_responsabilitat_familiar"]].head(10)

In [ ]:
# 3. descripcion global
df2["Pes_responsabilitat_familiar"].describe()

In [ ]:
# 4. cuantos NaN se han generado?
nulos = df2["Pes_responsabilitat_familiar"].isna().sum()
nulos

In [ ]:
# 5. de donde provienen los NaN ?
motivo_nulos = df2.loc[ df2["Pes_responsabilitat_familiar"].isna(),["Nombre_fills", "Edat"]].isna().sum()
motivo_nulos

In [ ]:
# 6. Comparamos la edad más alta con la más baja de empleados que tienen el mismo número de hijos, y asi vemos como la edad influye en el peso
df2.groupby("Nombre_fills")[
    ["Edat", "Pes_responsabilitat_familiar"]
].agg(["min", "max"])

7. Conclusiones

Utilidad analítica: permite combinar el número de hijos y la edad en un único indicador para analizar conjuntamente ambas características. Cuanto más mayor y más hijos, mayor es el peso de responsabilidad.

Decisiones tomadas: se multiplica Nombre_fills por Edat, de manera que el indicador aumenta tanto con el número de hijos como con la edad.

Casos límite o incoherentes: si Nombre_fills o Edat contiene un valor nulo, el indicador también será NaN. Además, diferentes combinaciones de edad y número de hijos pueden generar valores iguales:

- 60 años × 1 hijo = 60
- 30 años × 2 hijos = 60

Un valor 0 es válido cuando la persona no tiene hijos y no debe confundirse con un dato ausente.

# Exercici 4: Exportació i síntesi de resultats

> Utilitzant un bucle, exportar en 4 fitxers (format .csv o .xlsx) les dades corresponents a cada Grup Professional. Per exemple: dades_GrupA.csv, dades_GrupB.csv...

In [ ]:
for grup in df2['Grup Professional'].unique():

    df_grup = df2[df2['Grup Professional'] == grup]

    df_grup.to_excel(f'Empleats {grup}.xlsx', index=False)

> Crear i exportar un cinquè DataFrame (format .csv o .xlsx) que contingui, per a cada Grup Professional:

- Nombre total de treballadors.
- Salari mitjà.
- Edat mediana.

In [ ]:
# creamos las 3 variables
resumen = []

for grup in df2['Grup Professional'].unique():

    df_grup = df2[df2['Grup Professional'] == grup]

    total_treballadors = df_grup['ID'].count()
    salari_mitja = df_grup['Salari mensual_euros'].mean().round(2)
    edat_mediana = df_grup['Edat'].median()

    resumen.append({
        'Grup Professional': grup,
        'Nombre total de treballadors': total_treballadors,
        'Salari mitjà': salari_mitja,
        'Edat mediana': edat_mediana
    })

In [ ]:
df_resumen = pd.DataFrame(resumen)

# Ordenamos por grupo
df_resumen = df_resumen.sort_values(by='Grup Professional')

# Exportamos a excel
df_resumen.to_excel('Resum Per Grup Professional.xlsx', index=False)

> EXTRA

> Explora com exportar tots els DataFrames en un únic fitxer Excel, utilitzant:

» Una pestanya per a cada Grup Professional.

» Una pestanya addicional amb el resum agregat.

Usaremos ExcelWriter para exportar los dataframes en pestañas.

In [ ]:
with pd.ExcelWriter('Empleats Per Grup Professional.xlsx') as writer:

    # las 4 pestañas por grupo profesional
    for grup in df2['Grup Professional'].unique():

        df_grup = df2[df2['Grup Professional'] == grup]

        df_grup.to_excel(
            writer,
            sheet_name=grup,
            index=False
        )

    # la 5ª pestaña resumen
    df_resumen.to_excel(
        writer,
        sheet_name='Resum',
        index=False
    )

# Nivell 3 – Exploració visual i optimització aplicada

# Exercici 1: Exploració visual del dataset

> Aquest exercici se centra en crear una funció que ajudi a crear (i exportar) un gràfic automàticament per a cada columna del dataframe. Per exemple, un histograma/boxplot si la variable és numèrica, unes barres dels valors més freqüents si és categòrica i unes barres dels anys més freqüents si la dada està en format data.

In [ ]:
def eda(df):
    # Configuramos el estilo visual básico de Seaborn
    sns.set_theme(style="whitegrid")

    for col in df.columns:

        # excluimos estas columnas descriptivas
        if col.lower() in ['id', 'nom', 'cognoms', 'dni', 'variable']:
            continue

        # para columnas formato fecha
        if pd.api.types.is_datetime64_any_dtype(df[col]):
            anys = df[col].dt.year
            counts = anys.value_counts().sort_index()

            plt.figure(figsize=(8, 4))
            sns.barplot(x=counts.index.astype(str), y=counts.values, palette="magma", hue=counts.index.astype(str), legend=False)
            plt.title(f"Años más frecuentes: {col}")
            plt.xlabel("Año")
            plt.ylabel("Frecuencia")

        # para columnas numericas
        elif pd.api.types.is_numeric_dtype(df[col]):
            fig, axes = plt.subplots(1, 2, figsize=(12, 4))

            # Histograma
            sns.histplot(df[col].dropna(), kde=True, ax=axes[0], color="skyblue")
            axes[0].set_title(f"Histograma de {col}")

            # Boxplot
            sns.boxplot(x=df[col].dropna(), ax=axes[1], color="lightcoral")
            axes[1].set_title(f"Boxplot de {col}")

        # para columnas categoricas
        else:
            plt.figure(figsize=(8, 4))
            top_categorias = df[col].value_counts().head(10) # para mostrar los 10 valores más frecuentes
            sns.barplot(x=top_categorias.values, y=top_categorias.index.astype(str), palette="viridis", hue=top_categorias.index.astype(str), legend=False)
            plt.title(f"Categorías comunes: {col}")


        plt.tight_layout()
        plt.show()
        plt.close()

> Mostra el resultat de la funció en algun dels datasets d’exemple que conté el paquet seaborn. Per exemple, iris, penguins o titanic.

In [ ]:
df_penguins = sns.load_dataset("penguins")

eda(df_penguins)

# Exercici 2: Optimització de rutes (problema aplicat)

> Carrega l'arxiu matriu_distancies.xlsx a pandas de manera que les files i columnes siguin les ciutats i s'eliminin "Las Palmas de Gran Canaria" i "Palma".

In [ ]:
matriu_distancies = pd.read_excel('/content/drive/MyDrive/Colab Notebooks/matriu_distancies.xlsx', index_col=0)

matriu_distancies = matriu_distancies.drop(
    columns=['Las Palmas de Gran Canaria', 'Palma'],
    index=['Las Palmas de Gran Canaria', 'Palma']
)

matriu_distancies

> Desenvolupa una funció que:

Rebi: una ciutat d'origen i una ciutat de destinació.

Retorni: l'ordre de les ciutats visitades (ruta) i la distància total recorreguda.

La ruta s'ha de construir seguint una estratègia senzilla: anar sempre a la ciutat no visitada més propera fins a arribar a la destinació.

In [ ]:
def calcular_ruta_cercana(origen, destino):
    ruta = [origen]
    distancia_total = 0
    ciudad_actual = origen

    # Mientras no hayamos llegado a la ciudad de destino
    while ciudad_actual != destino:
        distancias_actuales = matriu_distancies.loc[ciudad_actual].copy()

        # Eliminamos de las opciones las ciudades que YA hemos visitado en la ruta
        opciones_validas = distancias_actuales.drop(labels=ruta, errors='ignore')

        # Buscamos la ciudad no visitada que tenga la distancia más pequeña
        proxima_ciudad = opciones_validas.idxmin()
        distancia_tramo = opciones_validas.min()

        # Actualizamos la ruta, sumamos los kilómetros y cambiamos de ciudad actual
        ruta.append(proxima_ciudad)
        distancia_total += distancia_tramo
        ciudad_actual = proxima_ciudad

    return ruta, distancia_total

In [ ]:
ruta_final, kms_totales = calcular_ruta_cercana('Barcelona', 'Bilbao')

print(f"ORDRE RUTA: {', '.join(ruta_final)}")
print(f"DISTANCIA RECORREGUDA: {kms_totales} km")